### ISSUE TITLE
How to go about multiple js files in Library

### ISSUE THREAD

**Issue by ZabelTech** [cljsjs/packages#106]
Hello,

i'm packaging this utility library for google maps:
https://github.com/printercu/google-maps-utility-library-v3-read-only
The code there is split up in many files, is there a task or common way to concatenate all the js file into one?
Because when I just copy them all in cljsjs/production and cljsjs/development and do build-jar, then later when i require the packkage in closurscript only one js file gets loaded actually loaded.

**Comment by martinklepsch** [comment]
Hey @ZabelTech, unfortunately there is no task to combine files built into `boot-cljsjs`. 

That said the libraries you're looking to package seem to be Closure advanced mode compatible, see #28 for details on what that means.

**Comment by martinklepsch** [comment]
@ZabelTech I'll close this now, feel free to reopen if there are any remaining questions.
