### ISSUE TITLE
[inferno] Could we eliminate externs?

### ISSUE THREAD

**Issue by ul** [cljsjs/packages#1084]
This release https://github.com/infernojs/inferno/releases/tag/1.6.0 states to be compatible with Google Closure compiler. I'm not deep into externs intrinsics, so my question is how could we leverage such compatibility? Just remove externs? Or any extra steps are required?

**Comment by Deraen** [comment]
No.

Inferno is using ES6 modules and ClojureScript doesn't support those, so only way to use it currently is as foreign lib. And when using foreign lib, externs are required as the code doesn't go through Closure optimization.

Closure compiler itself supports using ES6 modules in addition to Closure modules (`goog.provide`, `goog.require`), but ClojureScript only supports Closure modules.

**Comment by Deraen** [comment]
Or perhaps the ES6 support in Closure is usable with module processing https://clojurescript.org/guides/javascript-modules, I'm not sure

**Comment by ul** [comment]
Okay, then let's just wait for better opportunity. Thanks!
