### ISSUE TITLE
jQuery UI

### ISSUE THREAD

**Issue by ul** [cljsjs/packages#11]
would be nice to add

**Comment by martinklepsch** [comment]
Hi @ul, thanks for your suggestion.
If you could provide links to development and minified versions of jQuery UI as well as an externs file that would be of great help.

**Comment by ul** [comment]
Google says that there are no such externs :-( Placed in my todo list to generate them from their docs, but if anybody will do this earlier, it will be also very cool )))

**Comment by ul** [comment]
jQuery UI development, minified, and externs: https://gist.github.com/ul/2f18314c23bd8e5068bb
Not sure about externs format, please check.

**Comment by ul** [comment]
Please, take externs and source here https://github.com/tailrecursion/hoplon/tree/master/vendor/jquery-ui/src

**Comment by ul** [comment]
I see it presents in repo as for now.
