### ISSUE TITLE
Can I use yarn?

### ISSUE THREAD

**Issue by zarkone** [cljsjs/packages#1118]
Hello! 

Can't update `epub.js` dev version, not installable with `npm` currently: see https://github.com/futurepress/epub.js/issues/606

I've seen that someone attempted to use `yarn`: https://github.com/cljsjs/packages/pull/1018 so decided to ask if it ok to use `yarn` in build script?

Thanks!

**Comment by miikka** [comment]
I'd say it's preferable to use `npm` for consistency unless there's some kind of exceptional situation that prevents using it.

I'll close this since the problem with epub.js has been resolved anyway.
