### ISSUE TITLE
Bad react externs

### ISSUE THREAD

**Issue by thheller** [cljsjs/packages#1129]
I'm currently working on enabling the Closure `:check-types` compiler option again. While doing so it uncovered some bad annotations in the `react` package externs.

```
CLOSURE-WARNING: EXTERNS:/Users/zilence/.m2/repository/cljsjs/react-dom/15.4.2-2/react-dom-15.4.2-2.jar!/cljsjs/react-dom/common/react-dom.ext.js[27:11]
	Bad type annotation. Unknown type React.ReactComponent


CLOSURE-WARNING: EXTERNS:/Users/zilence/.m2/repository/cljsjs/react-dom/15.4.2-2/react-dom-15.4.2-2.jar!/cljsjs/react-dom/common/react-dom.ext.js[30:12]
	Bad type annotation. Unknown type React.ReactComponent


CLOSURE-WARNING: EXTERNS:/Users/zilence/.m2/repository/cljsjs/react-dom/15.4.2-2/react-dom-15.4.2-2.jar!/cljsjs/react-dom/common/react-dom.ext.js[43:11]
	Bad type annotation. Unknown type React.ReactComponent


CLOSURE-WARNING: EXTERNS:/Users/zilence/.m2/repository/cljsjs/react-dom/15.4.2-2/react-dom-15.4.2-2.jar!/cljsjs/react-dom/common/react-dom.ext.js[70:11]
	Bad type annotation. Unknown type React.ReactComponent


CLOSURE-WARNING: EXTERNS:/Users/zilence/.m2/repository/cljsjs/react-dom/15.4.2-2/react-dom-15.4.2-2.jar!/cljsjs/react-dom/common/react-dom.ext.js[71:11]
	Bad type annotation. Unknown type React.ReactElement


CLOSURE-WARNING: EXTERNS:/Users/zilence/.m2/repository/cljsjs/react-dom/15.4.2-2/react-dom-15.4.2-2.jar!/cljsjs/react-dom/common/react-dom.ext.js[74:12]
	Bad type annotation. Unknown type React.ReactComponent


CLOSURE-WARNING: EXTERNS:/Users/zilence/.m2/repository/cljsjs/react/15.4.2-2/react-15.4.2-2.jar!/cljsjs/react/common/react.ext.js[212:22]
	@extends used without @constructor or @interface for React.PureComponent
```

They work but that should probably be fixed at some point.

I'll create a PR when I find the time.

**Comment by tiagob** [comment]
+1

**Comment by Deraen** [comment]
React ext provides `React.Component`, I think these were incorrectly renamed when splitting DOM api to separate file. I fixed the names for 16.1.0. https://github.com/cljsjs/packages/commit/cd41028256f4762ce7c6de9c5d314ded3dc2da5b

This hopefully works, IF externs can refer to other extern files for types.

**Comment by Deraen** [comment]
I only fixed ReactComponent names, others are  still broken. I wonder if it is possible to use Closure to validate externs so we can get these problems?

**Comment by thheller** [comment]
The warnings above are produced by Closure but from a regular build. Not sure if Closure validates Externs if you compile them without actual code? It does have a checksOnly mode so it should be possible.

https://github.com/thheller/shadow-cljs/blob/b0304c563ec0073074360291d4bcbf7e9973c176/src/main/shadow/build/closure.clj#L1042

**Comment by Deraen** [comment]
I can easily validate the extern by calling `cljs.closure/build` with very simple JS file and using advanced optimization. However, adding check-types warning will cause loads of warnings from Cljs side, so seems to be hard for now to require that Cljsjs packages wouldn't cause these problems.

**Comment by Deraen** [comment]
Hm, well, warnings don't cause the build to fail so I think I can enable those.

**Comment by Deraen** [comment]
I have implemented simple validation task to boot-cljsjs now: https://github.com/cljsjs/boot-cljsjs/blob/master/src/cljsjs/impl/closure.clj

Running `boot package` on React folder now shows warnings from Closure:

```
Nov 09, 2017 9:28:02 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: externs.zip//es6.js:165: WARNING - variable Math.imul redefined with type function(number, number): number, original definition at file:/home/juho/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/externs.js:11 with type function(?, ?): ?
Math.imul = function(value1, value2) {};
^^^^^^^^^

Nov 09, 2017 9:28:02 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 0 error(s), 84 warning(s), 76.6% typed

```

No warnings related to React externs after fixes. Full output here: https://circleci.com/gh/cljsjs/packages/2716

**Comment by thheller** [comment]
Pretty neat.

You might want to consider just calling the Closure Compiler directly. Really no need to involve `cljs.closure/build` in this since it does a whole bunch of stuff you don't need.

**Comment by Deraen** [comment]
It also finds all the `deps.cljs` files from classpath, and gets list of foreign-libs and externs from there, and loads all those to Closure. Going through `deps.cljs` files is easiest as Cljsjs packages can have dependencies, i.e. react-leaflet depends on react and react-dom, and its extern might refer to React extern.

**Comment by thheller** [comment]
Won't they already be verified in their own packages?

I don't know anything about your setup here so you'll know best what to do.

**Comment by Deraen** [comment]
Yes externs will be verified  in each package, but single extern file can't be verified alone, as it might have dependencies. Like ReactDOM extern depends on React extern, which is in another package (though they are packaged from same folder).

I could call Closure compiler directly, but I think this is much simpler, and I don't think the extra things Cljs does matter anyway.
