### ISSUE TITLE
How to control whether one is using React production build

### ISSUE THREAD

**Issue by vemv** [cljsjs/packages#1132]
Hello!

There's a 'production' build of react, which performs faster and does not emit warnings. This seems to be controlled by the `__DEV__` and/or `NODE_ENV` variables.

https://facebook.github.io/react/docs/optimizing-performance.html

When including react via cljsjs, it's not quite clear which version is one pulling in, and how to specify one or the other for different environments (lein builds etc).

Cheers - Victor

**Comment by Deraen** [comment]
`react.min.js` is used when using `:optimization :advanced`, else `react.js` is used. React.min.js compiled in production mode.

**Comment by vemv** [comment]
Hi Deraen, thanks for the answer!

I see. This seems to couple things that could be offered separately - generally one would expect `:optimizations` to control Closure optimization level, not to control which asset am I pulling.

This might make some custom testing workflows more difficult.

Possible to control this separately?

In any case, this detail seems worth documenting.

Cheers - Victor

**Comment by vemv** [comment]
I found a new manifestation of this issue:

say I want to run my test suite under `:advanced` optimizations, which doesn't seem an extravagant choice (one may naturally want to catch externs/minifications problems before they hit production).

We use https://github.com/bensu/cljs-react-test in our codebase. That library, conversely uses the React.addons.TestUtils code, which is not externed in https://github.com/cljsjs/packages/blob/7569ab53c0df0684f8395da0cb3aa71eda19cb8f/react/resources/cljsjs/react/common/react.ext.js .

The comment itself says:

>  Only usable with non-minified version of React-with-addons

One can wonder - why? Was this a choice or a constraint?

copy-pasting those externs into my project may just work, anyway it sems to me that there's room for improvement here - and for a library as important as React

**Comment by Deraen** [comment]
@vemv TestUtils were only included in non-minified React with-addons build. But please notice, that with-addons version doesn't exist anymore. Test utils are currently not packaged on Cljsjs, as React doesn't provide browser ready JS for this part.

**Comment by vemv** [comment]
Thanks for the feedback!

Looks like, for my particular case (where I want to keep using the deprecated `[cljsjs/react-with-addons "15.3.1-0"]` for a while), I'll have to fork this old library and make it always serve unoptimized assets.

So I could choose between `[cljsjs/react-with-addons "15.3.1-0"]` for production env, and `[vemv/react-with-addons "15.3.1-0"]` for test env.

Should work. Anyway, this is quite a custom need by now so I'll close the issue
