### ISSUE TITLE
Possible typo for react-ultimate-pagination

### ISSUE THREAD

**Issue by tomjkidd** [cljsjs/packages#1156]
I was doing some work to assess using this for a project I'm working on, and I noticed a potential
[typo](https://github.com/cljsjs/packages/blob/master/react-ultimate-pagination/resources/cljsjs/react-ultimate-pagination/common/react-ultimate-pagination.ext.js#L6), where `PREVIOS_PAGE_LINK` is used when I expected `PREVIOUS_PAGE_LINK`.

If this isn't a typo introduced as part of this lib, sorry to create noise.

**Comment by xiongtx** [comment]
Definitely [seems to be a typo](https://github.com/ultimate-pagination/react-ultimate-pagination-material-ui/blob/098aa8be88d5553c300ded28e7cc8eb15aa83ce8/src/react-ultimate-pagination-material-ui.js#L41) in the `cljsjs` version. I see that the [externs aren't auto-generated](https://github.com/cljsjs/packages/blob/096ca1a7cb7b359385aa117a044ba4dfa9fbda30/react-ultimate-pagination/resources/cljsjs/react-ultimate-pagination/common/react-ultimate-pagination.ext.js#L6), so the typo must have slipped in :man_shrugging:.

**Comment by plexus** [comment]
This is actually an upstream bug, it's not just in the externs, it's in the package itself.

https://github.com/ultimate-pagination/react-ultimate-pagination/issues/1

I'll see if we can upgrade, this has been fixed a long time.

**Comment by tomjkidd** [comment]
Thank you!
