### ISSUE TITLE
React Bootstrap

### ISSUE THREAD

**Issue by elaatifi** [cljsjs/packages#12]
Hello,

It would be nice to add React Bootstrap

**Comment by martinklepsch** [comment]
Hi @elaatifi. I agree that it'd be nice to have that packaged but since Bootstrap is more of an application framework than a library and also ships with a lot of CSS it'll be hard to package that in a way that's usable for everyone.

**Comment by elaatifi** [comment]
Thank you @martinklepsch. IMO there is two parts in Bootstrap, the CSS framework and JS components, ReactBootstrap is concerned by the port of the second part to React.
If someone is already using the CLJSJS package of React can not use ReactBootstrap unless it's packaged too.
Anyway if someone is interested here is an attempt that seems to work :) https://github.com/elaatifi/packages/tree/react-bootstrap/react-bootstrap (include the extern file)

**Comment by sritchie** [comment]
You might also want to check out https://github.com/racehub/om-bootstrap, my port of most of the components from React-Bootstrap to ClojureScript.

**Comment by sventech** [comment]
Thanks, @elaatifi -- I'd also like to see the JS part of ReactBootstrap available. could you make a pull request? Perhaps someone would do a code review and include it.

**Comment by elaatifi** [comment]
@martinklepsch did you checked this https://github.com/elaatifi/packages/blob/react-bootstrap/react-bootstrap/resources/cljsjs/common/react-bootstrap.ext.js

**Comment by uwo** [comment]
@elaatifi Thanks! Was also looking for this.

**Comment by rundis** [comment]
I'm also very keen on getting this in (plus updating the externs file to include the latest from react-bootstrap, CollapsableNav for one)

**Comment by martinklepsch** [comment]
Hey. Sorry for my unresponsiveness. I didn't quite know how to handle this as I'm not using it etc. Would you mind creating a PR based on your branch (rebased against master) so we can continue discussion/testing there? Also if people in this thread used @elaatifi's package, it would be helpful to get a show of hands if it worked as advertised etc. 

Thanks :+1:

**Comment by rundis** [comment]
Seems @uwo had a more urgent need than me : https://github.com/uwo/react-bootstrap
I only briefly tried using it (in combination with quiescent). The small things I tried work, but unfortunately my current project uses a newer version of react-bootstrap so I had to abort mission (temporarily). I'm happy to volunteer in trying out an updated version  :)

**Comment by uwo** [comment]
@rundis Ah, I created that as a short term solution for myself so I could promote https://clojars.org/org.clojars.uwo/react-bootstrap and use it in my project.clj.  I'd much prefer to have it centralized here, of course.  

@martinklepsch 
It worked as advertised, though I haven't spent an extensive amount of time with it.

**Comment by martinklepsch** [comment]
I merged #102 yesterday, please let me know if it can be improved in any way. Ideally by making a PR or creating a new issue. I'll close this now as there now is a `react-bootstrap` package.

@uwo Sorry for letting this slip here and not merging your package. Please create a pull request next time, usually I look at/review PRs around once a week. :+1:
