### ISSUE TITLE
Parinfer/paredit add-on are missing for CodeMirror

### ISSUE THREAD

**Issue by ertugrulcetin** [cljsjs/packages#1214]
Could you add parinfer and paredit add-on for CodeMirror?

**Comment by Deraen** [comment]
Parinfer addon is not part of Codemirror. There is no official library to package, there are several cljs libs that extract the code from Parinfer demo site.

https://github.com/hiram-madelaine/codemirror-parinfer
https://github.com/metosin/codemirror-parinfer

**Comment by Deraen** [comment]
I'm not familiar with Paredit but looks like the CodeMirror support for that is implmented in Cljs so Cljsjs package doesn't make sense: https://github.com/achengs/paredit-cm Just include the cljs lib and set up Codemirror options: https://github.com/achengs/paredit-cm/blob/master/resources/demo/js/keymap-paredit-cm.js
