### ISSUE TITLE
moment-timezone is missing some externs

### ISSUE THREAD

**Issue by bago2k4** [cljsjs/packages#1291]
I included `[cljsjs.moment-timezone]` in my project, when i  call `(.. moment -tz guess)` in my advanced compiled env i get this:
`Uncaught TypeError: moment.tz.rr is not a function`.

Looking at the ext.js file there is only `.tz`, all the sub functions and properties are missing.

I'll add them if I have some time, for now i just wanted to open an issue.

**Comment by TylerHansen** [comment]
I also ran into this issue, specifically evaluating `(.guess (.-tz js/moment))`. I added the following to my project's externs to fix the issue, not doing a PR because it's only handling my specific use case:

```
var moment = { "tz": {} };
moment.tz.guess = function() {};
```

**Comment by ducky427** [comment]
see PR #1379

**Comment by bago2k4** [comment]
Thanks @ducky427 closing the issue
