### ISSUE TITLE
New package request: Pixi.js

### ISSUE THREAD

**Issue by xeqi** [cljsjs/packages#13]
I would enjoy a properly packaged version of pixijs.  https://github.com/GoodBoyDigital/pixi.js/

**Comment by martinklepsch** [comment]
The biggest hurdle of packaging a new lib is finding proper extern files.
I found [this issue](https://github.com/GoodBoyDigital/pixi.js/pull/866) in the pixi project with a link to probably incomplete [externs](http://pastebin.com/zz9pgKTV).

@xeqi do you by any chance have externs for this library around from previous occasions where you used it?

**Comment by xeqi** [comment]
I do not have one yet. Looking around online I can find a more complete attempt at one, but it doesn't have a clear license.

Is there a guide for building one? Is it really about making a javascript file where all the variables and properties are functions/objects?

**Comment by shaunlebron** [comment]
@xeqi started a wiki page based on what I was able to glean from examples and Google Closure docs, hope others will add to it: https://github.com/cljsjs/packages/wiki/Creating-an-externs-file

**Comment by martinklepsch** [comment]
Oh wow, that's amazing, thank you guys! :gem:

**Comment by martinklepsch** [comment]
By the way, we've figured out a good way to package Closure libs (see `openlayers`) it seems that Pixi is also usable also "native" Closure library? If so it'd be very easy to package :+1:

**Comment by boutros** [comment]
Hi,
I'm about to continue work again on [my cljs wrapper for pixi](https://github.com/boutros/pi). It would be great to have it packaged.

I have no experience in making externs yet, but I'm willing to look into it.

Has anyone made any prorgess? Anything I can do to help out?

**Comment by jmmk** [comment]
I've just made a pull requests for PIXI.js 3.0.6 here: https://github.com/cljsjs/packages/pull/131

I didn't do any work on the externs; the refactoring they did from version 2 to version 3 allowed it to be automatically generated from http://www.dotnetwise.com/Code/Externs/ without any trouble.

**Comment by boutros** [comment]
:smile:

**Comment by martinklepsch** [comment]
Closing this in favor of #131
