### ISSUE TITLE
[Request] MQTT.js

### ISSUE THREAD

**Issue by philip-healy** [cljsjs/packages#1348]
https://github.com/mqttjs/MQTT.js

**Comment by Frozenlock** [comment]
If you don't want to wait for a cljsjs package, you can simply download the [minified file](https://unpkg.com/mqtt@2.13.0/dist/mqtt.min.js) and load it in the browser before the cljs app.

As for the externs needed by your project, you can generate them by using [lein-externs](https://github.com/ejlo/lein-externs).
