### ISSUE TITLE
boot package failing in parinfer

### ISSUE THREAD

**Issue by shaunlebron** [cljsjs/packages#1374]
Running `boot package` in `/parinfer` gives an exception related to not finding `string/ends-with?`:

```
             java.lang.RuntimeException: No such var: string/ends-with?
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such var: string/ends-with?, compiling:(asset_minifier/core.clj:38:19)
             clojure.lang.ExceptionInfo: java.lang.RuntimeException: No such var: string/ends-with?, compiling:(asset_minifier/core.clj:38:19)
```

Running `boot -V` shows that I'm on Clojure 1.7.0, explaining why `string/ends-with?` was not found:

```
#http://boot-clj.com
#Mon Oct 23 20:54:21 CDT 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.7.2
```

Should there be a `boot.properties` in this repo that ensures we're using 1.8.0?

**Comment by Deraen** [comment]
You might have the Clojure version defined in your `~/.boot/boot.properties`? The default is 1.8.0.

CI works and the only way to ensure Boot/Clojure version for each package here would be to add `boot.properties` file to each package folder.

**Comment by shaunlebron** [comment]
Interesting, I deleted `~/.boot/boot.properties` which had 1.7.0, ran boot, and a new boot.properties was created with 1.8.0.  I wonder what will cause it to auto-update the clojure version.

thank you!
