### ISSUE TITLE
PouchDB

### ISSUE THREAD

**Issue by fehrenbach** [cljsjs/packages#14]
Would anyone be up for packaging [PouchDB](https://github.com/pouchdb/pouchdb)?

Source:
https://github.com/pouchdb/pouchdb/releases/download/3.2.1/pouchdb-3.2.1.js
Min:
https://github.com/pouchdb/pouchdb/releases/download/3.2.1/pouchdb-3.2.1.min.js

I have successfully used an autogenerated externs file before. That was quite some time ago, though.

Also, I just had a look at the license (Apache). It allows for redistribution, but requires the license text to be redistributed as well. How do other libraries deal with that? Will boot include that in the jar by itself?

**Comment by martinklepsch** [comment]
I think that'd be a great addition. Always meant to use Pouch in a Clojurescript project :)

Boot adds license information to the `pom.xml` file so essentially the jars are redistributed under the same terms. I'm not sure if the `jar` task uses the URL in the `build.boot` file to download the license and add it to the jar. If not that should be easy to do :)

@fehrenbach If you could provide an externs file that'd be extremely helpful.
Probably we should write some utility that helps with generating those extern files.

Thanks for your suggestion!

**Comment by fehrenbach** [comment]
I'm afraid I don't have one. It's been a long time. Two or three years ago. I don't think my externs file from back then is still applicable. Come to think of it, was that even pouch? Might have been the js client shipped with couch...

Yesterday I stumbled upon this externs generator: http://www.dotnetwise.com/Code/Externs/
It produces some output for PouchDB, but I have not tried to actually use it, yet.

I might do it in a couple of weeks. This is all for a side project that has been started over and over again on whatever my latest idea for sensible UI technology was. It never got anywhere. I'm back to browser + ClojureScript, this time with om.

**Comment by martinklepsch** [comment]
> Yesterday I stumbled upon this externs generator: http://www.dotnetwise.com/Code/Externs/ It produces some output for PouchDB, but I have not tried to actually use it, yet.

Yeah, that's an option. Maybe we can put something like that together based on node so it can be encapsulated in a task.

> This is all for a side project that has been started over and over again on whatever my latest idea for sensible UI technology was. It never got anywhere. I'm back to browser + ClojureScript, this time with om.

That sounds familiar haha.

**Comment by fasiha** [comment]
Thanks for this @fehrenbach!

Question: I’d like to use some PouchDB plugins like [authentication](https://github.com/nolanlawson/pouchdb-authentication) and [upsert](https://github.com/pouchdb/upsert).

Would it make sense to add their API calls to the PouchDB externs file in cljsjs? If so, I can submit a patch. Given the richness of the pouchdb ecosystem, and the fact that each plugin extends the API by only a handful of functions, this feels like the better choice versus a separate cljsjs dependency for each plugin?

**Comment by fehrenbach** [comment]
You would still need the code for the plugins, right? 
I would recommend to make them proper cljsjs packages. That way you don't have to muck about with script tags and the like. 

On the other hand, additional external do not hurt (much). If you want to add them feel free. I haven't used ClojureScript in a while and this package is not up to date with the latest PouchDB. You might want to update that while you're at it. I don't think the API has changed, so you just need to bump the version, update the checksums, and hope that the build steps still work.
