### ISSUE TITLE
Go Blocks For Core.Async?

### ISSUE THREAD

**Issue by JimTheMan** [cljsjs/packages#1414]
Hey! This might be a dumb question, but is there a cljs implementation of core.async with go blocks? I was watching a video with david nolan talking about core.async where he was talking about go blocks the whole time. Is that a different library for clojurescript or was he talking about the JVM clojure? Thanks!

**Comment by Deraen** [comment]
Core.async is Clojure library, not JavaScript. And yes, it is available for Cljs.

**Comment by JimTheMan** [comment]
Thanks @Deraen, but I think your response does not make any sense and does not answer my question. :)

**Comment by Deraen** [comment]
> Is that a different library for clojurescript or was he talking about the JVM clojure?

No, no.

It is the same library for both JVM and JS.

**Comment by JimTheMan** [comment]
But then why is it completely different syntax?

**Comment by JimTheMan** [comment]
In the JVM version I use go  blocks, but they are not in the examples here.

**Comment by Deraen** [comment]
I'm not sure what you are asking about. I would recommend [Clojurians Slack](http://clojurians.net/) or https://clojureverse.org/ for better place for general questions. Core.async doesn't really relate to Cljsjs.
