### ISSUE TITLE
[cljsjs.react-select] Undefined nameToPath for react

### ISSUE THREAD

**Issue by Atsman** [cljsjs/packages#1422]
Hello,

I am trying to use [cljsjs.react-select].

I am getting this error `Undefined nameToPath for react`.

If we check the source, we will see that 

```clojure
:requires ["react" "prop-types"]
```

instead of
```clojure
:requires ["cljsjs.react" "cljsjs.prop-types"]
```

Should i replace that?

**Comment by Atsman** [comment]
https://github.com/cljsjs/packages/pull/1423

**Comment by Atsman** [comment]
i checked localy, problem is fixed

**Comment by Deraen** [comment]
If you have problems, make sure you are using recent React and Prop-types packages, and recent ClojureScript.

**Comment by Atsman** [comment]
@Deraen, yeah you right, with latest deps everything is ok. I am curios why u decided to break such semantic, because, looks like most libraries provides names with cljsjs, but here is exception. Feels not good, it is better to provide both if you decided to change the name. While investigating and googling what is wrong, u see that everywhere people use cljsjs. That is one of the reason why cljs is so frustrating for new developers.

**Comment by Deraen** [comment]
@Atsman Naming change is required to be able to switch between Node modules and Cljsjs packages without changing the libraries:

For context:
https://clojurescript.org/news/2017-07-12-clojurescript-is-not-an-island-integrating-node-modules
https://clojurescript.org/news/2017-07-30-global-exports

**Comment by Atsman** [comment]
@Deraen, I got the point, thank you for links. I just think that we could do that in more smooth way, instead of changing entirely, we should export both old name and new one. So that it is backward compatible. Something changes everyday, and if u gonna break the public interface every time, it is pain for developers who do not care about npm, yarn or something else. I guess there may be some potential drawbacks of such approach. But anyway it is as it is. Thanks for links.

**Comment by Atsman** [comment]
@Deraen look at webpack for example, it supports imports, amd, commonjs, umd. They do not drop support of old module specifications as soon as some hipster post article about new approach. And in some sense, js tools more reliable than what we have in cljs world. And that fact makes me angry.

**Comment by Deraen** [comment]
The naming change is non breaking. New packages are fully backwards compatible. New React and Prop-types provide the old `cljsjs.*` names. Updated React 15 is also available, so you don't need to update to React 16.

The one thing that can cause breakage, is if you have conflicting dependencies,  (i.e. Reagent/prop-types require React 15.6 and React-select 15.3), in this case, you need to:

1) need to update React version on your project to ensure you get correct version, or
2) exclude React from React-select dependency, or
2) update React-select or other package to use more recent React

In any case `lein deps :tree` is your friend on checking if you have conflicting dependencies.
