### ISSUE TITLE
unable to require cljsjs.google-maps

### ISSUE THREAD

**Issue by ThomasDeutsch** [cljsjs/packages#146]
I am unable to require the cljsjs.google-maps package.

I added the dependency to my project.clj
```clj
[cljsjs/google-maps "3.18-1"]
```

and required the google-maps package in my namespace like this:
```clj
(ns myapp.service
  (:require
    cljsjs.google-maps)
```

I get this compiler error, where the package is listed with an underscore?
```
clojure.lang.ExceptionInfo: No such namespace: cljsjs.google-maps, could not loc
ate cljsjs/google_maps.cljs or cljsjs/google_maps.cljc at line 1
```

I am using
```clj
[org.clojure/clojure "1.7.0-beta2"]
[org.clojure/clojurescript "0.0-3211"]
```

**Comment by martinklepsch** [comment]
@ThomasDeutsch Did you figure it out?

`cljsjs/google-maps` is externs-only:
>The jar only provides an extern file required for advanced compilation. The Google Maps js API will still need to provided through some other mechanism.

**Comment by ThomasDeutsch** [comment]
yes, i was about to leave this comment. Thanks for your help.

**Comment by BWStearns** [comment]
@martinklepsch as someone running into the same issue, how do you provide the Google Maps js API?
