### ISSUE TITLE
CodeMirror plugins

### ISSUE THREAD

**Issue by stask** [cljsjs/packages#154]
CodeMirror has plugins (like addon/edit/matchbrackets.js for instance). What's the right way to include them?

Thanks,

**Comment by Deraen** [comment]
Those are not currently packaged.

It requires generating `deps.cljs` entries for addons, the same way as is done for mode files: https://github.com/cljsjs/packages/blob/master/codemirror/build.boot#L27-L43

**Comment by martinklepsch** [comment]
Have these been packaged with #199?

**Comment by ducky427** [comment]
I used an addon with the latest codemirror `5.6.0-0`. For example:

```clojure
(ns application.core
  (:require [cljsjs.codemirror]
            [cljsjs.codemirror.addon.display.placeholder]))
```

**Comment by Deraen** [comment]
I believe this has been implemented.
