### ISSUE TITLE
Request: Support for BitAuth

### ISSUE THREAD

**Issue by xcthulhu** [cljsjs/packages#161]
It would be awesome if cljsjs had a client-side bitauth package

**Comment by xcthulhu** [comment]
I ended up just wrapping this library in ClojureScript along, and rewrote it in Clojure with an identical API.

https://github.com/xcthulhu/clj-bitauth

**Comment by crisptrutski** [comment]
Nicely done!

**Comment by xcthulhu** [comment]
Haha spoke too soon (tried to put it into production and the thing fell on its face).  Spent the morning making a CLJSJS implementation.  I'll make sure my tests in clj-bitauth are still passing using the cljsjs package...
