### ISSUE TITLE
Clipboard.js externs are out of date

### ISSUE THREAD

**Issue by frenata** [cljsjs/packages#1742]
https://github.com/cljsjs/packages/blob/e395f1ebdaef57ed60a611cebc6d9bde7943a717/clipboard/resources/cljsjs/clipboard/common/clipboard.ext.js#L9

should be changed from `Clipboard` to `ClipboardJS`, at least.

See https://github.com/zenorocha/clipboard.js/issues/468 for background on the issue.

**Comment by shen-tian** [comment]
This can be closed?

**Comment by frenata** [comment]
Looks like it, thanks! Apparently I missed the initial notification.

Closed by #1795.
