### ISSUE TITLE
OpenLayers: js files not getting loaded

### ISSUE THREAD

**Issue by casperc** [cljsjs/packages#190]
I am having a fair bit of trouble getting the OpenLayers package to work. When adding the dependency it never seems to actually include the OL js in the application. 

It does not fail when compiling, but trying to do anything fails.

I have a blank namespace and am adding the require from the readme:

     (:require [goog.dom :as dom]          ; Closure
                [ol.animation :as anim]) 

This fails in the repl though when trying to load the namespace. I can also see that when I load the app in the browser (via figwheel and optimizations: none), the js files are not included. 

I am tried to add a require on [cljsjs.openlayers] in my :main file, however in that case the compilation fails. Same for [cljsjs.ol].

So am I missing something obvious here?

**Comment by casperc** [comment]
It seems I can get the code to load by adding 

    [ol.animation :as anim]
    [ol.Map :as m]

to my main file. Otherwise the js files are not loaded. The REPL still complains though, even though the files are loaded.

**Comment by martinklepsch** [comment]
Unfortunately I haven't used OpenLayers yet so can't help myself.
Maybe @olivergeorge or @ul have suggestions?

**Comment by olivergeorge** [comment]
Just a quick link in passing, there's some example code using this library here:

* https://github.com/condense/openlayers-om-components/
* https://github.com/IMASau/geonetwork-data-submission-tool/tree/master/MetadataClient

**Comment by casperc** [comment]
I forgot to update this. It seems I had a conflict in the project I was trying to load the map from, but it works when creating a new project. Closing the issue.
