### ISSUE TITLE
React-with-addons missing CSSTransitionGroup

### ISSUE THREAD

**Issue by talgiat** [cljsjs/packages#20]
Seems like the react-with-addons extern is missing many public methods of addons:
CSSTransitionGroup
LinkedStateMixin
PureRenderMixin
TransitionGroup
batchedUpdates
cloneWithProps
update

This breaks our code in advanced compilation since we use transition group

**Comment by martinklepsch** [comment]
@talgiat thanks for the report, I just pushed a new version with CSSTransitionGroup. Will look into the rest you mentioned.

**Comment by martinklepsch** [comment]
I added the CSSTransitionGroup extern. If you need the rest it'd be great if you could provide a PR, It wasn't clear to me what the arguments/return values of those functions are from looking at [the docs](http://facebook.github.io/react/docs/addons.html)

**Comment by talgiat** [comment]
That fixed at. We don't need the other ones, but for completeness I'd recommend to add them.
