### ISSUE TITLE
Can't use fastclick package

### ISSUE THREAD

**Issue by wkf** [cljsjs/packages#200]
The `fastclick` package seems to exist in the repo, but not on clojars. I packaged up fastclick about a month ago, but maybe there was something I missed. Is there anything I can do to fix it? 

Sorry for the trouble... thanks!

**Comment by crisptrutski** [comment]
Thanks for pointing this out, have just published `1.0.6-0`

**Comment by wkf** [comment]
Right on, thanks for the quick reply :)
