### ISSUE TITLE
Once you package the jar, how to test it in a project?

### ISSUE THREAD

**Issue by kenfehling** [cljsjs/packages#205]
I'm creating a package and I've succeeded in creating a jar using `boot package build-jar` but I'm not sure how to test it. I'm using leiningen. What's the simplest way to include the jar? Is there something besides leiningen I should be using instead? Thanks.

**Comment by martinklepsch** [comment]
Hey Ken, once you ran build-jar the read me contains the usual vector of
project name and version that you can just add to your project.clj. The
build-jar task not only builds the jar but also copies it into your local
maven cache (usually ~/.m2). Hope that helps :)

**Comment by kenfehling** [comment]
Excellent! It helped very much, thank you.
