### ISSUE TITLE
Leaflet and Mapbox

### ISSUE THREAD

**Issue by bsima** [cljsjs/packages#21]
I've got a branch started for Leaflet [here](https://github.com/bsima/packages/tree/leaflet/leaflet), however I'm having trouble with the `sift` step of the packaging process.

Leaflet comes pre-built in a [`leaflet-0.7.3.zip`](http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.3.zip) which looks like this when unzipped:

```bash
.
├── images
│   ├── layers-2x.png
│   ├── layers.png
│   ├── marker-icon-2x.png
│   ├── marker-icon.png
│   └── marker-shadow.png
├── leaflet-src.js
├── leaflet.css
└── leaflet.js
```

So I was thinking that my `sift` task should look like this:

```clojure
(sift :move {#"leaflet\.js" "cljsjs/production/leaflet.js"
             #"leaflet-src\.js" "cljsjs/development/leaflet-src.js"
             #"leaflet\.css" "cljsjs/common/leaflet.css"
             #"images" "cljsjs/common/images"
             })
(sift :include #{#"^cljsjs"})
```

However when I run that I get a `java.lang.IllegalArgumentException: No implementation of method: :path of protocol: #'boot.tmpdir/ITmpFile found for class: nil`. I don't understand what this means but I assume this means that I'm not properly matching the filename? I manually created `cljsjs/{production,development,common}` but that didn't solve it either.

[The full stack trace is here](https://gist.github.com/564b23aa85f9b8be2f61)

Slightly related question, what is the best workflow for creating these packages? Is it to do the `download`, `sift`, and `deps-cljs` tasks from the repl and then copy into `build.boot`? I have the full workflow figured out from the command line with `curl` and `unzip` and whatnot, but not from the repl.

Once I get leaflet packaged I can package mapbox because mapbox depends on leaflet.

**Comment by bsima** [comment]
Okay thanks, I'll tackle this tonight.

> I just go ahead write it all into build.boot, see if it works, repeat.

That's what I've been doing - I'll just keep on keepin' on.

**Comment by martinklepsch** [comment]
Closing in favor of #29
