### ISSUE TITLE
[cljsjs/fixed-data-table "0.4.1-0"] not in clojars

### ISSUE THREAD

**Issue by rundis** [cljsjs/packages#214]

**Comment by crisptrutski** [comment]
Your desire is here: [0.4.1-0](https://clojars.org/cljsjs/fixed-data-table/versions/0.4.1-0)
You may prefer [0.4.6-0](https://clojars.org/cljsjs/fixed-data-table/versions/0.4.6-0)

(Unfortunately this seems to have confused Clojars.. it seems to just use date to determine "latest")
