### ISSUE TITLE
cljsjs/react-easy-crop Incompatible with Shaddow-CLJS

### ISSUE THREAD

**Issue by Caoimhin89** [cljsjs/packages#2157]
I get the following error when building my project with cljsjs/react-easy-crop

```
The namespace was provided via :foreign-libs which is not supported.
                                    Please refer to https://shadow-cljs.github.io/docs/UsersGuide.html#cljsjs for more information.
```

**Comment by Deraen** [comment]
Yes, Shadow-cljs doesn't support any Cljs foreign-libs or Cljsjs package, as the guide says. You just use npm to install packages directly, nothing to fix here.
