### ISSUE TITLE
CI/clojars: Cant create new projects

### ISSUE THREAD

**Issue by 2knu** [cljsjs/packages#2187]
Can you take a look on it @Deraen 

Exception:
```
Access denied to: https://clojars.org/repo/cljsjs/chartjs-adapter-date-fns/2.0.0-0/chartjs-adapter-date-fns-2.0.0-0.jar.asc, ReasonPhrase: Forbidden - Group 'cljsjs' isn't verified, so can't contain new projects (see https://git.io/JOs8J).
```

**Comment by Deraen** [comment]
Yeah, we'll need to start using reverse-domain name group names, probably `io.github.cljsjs`. I've requested the group names and I'll configure the CI to support those. Probably the website will need a fix also.

**Comment by Deraen** [comment]
New packages can use `io.github.cljsjs` group: https://clojars.org/io.github.cljsjs/chartjs-adapter-date-fns
