### ISSUE TITLE
Chance.js

### ISSUE THREAD

**Issue by shaunlebron** [cljsjs/packages#26]
[Chance.js](http://chancejs.com/) - random generator library

- dev: http://chancejs.com/chance.js
- min: http://chancejs.com/chance.min.js
- externs: [chance.ext.js](https://gist.github.com/shaunlebron/7ea4610c2fe6e82f385f)

**Comment by shaunlebron** [comment]
updated post with externs file

**Comment by martinklepsch** [comment]
@shaunlebron thanks. Are you planning to make that into a PR?

**Comment by shaunlebron** [comment]
working on it, will post PR

**Comment by martinklepsch** [comment]
Let me know if you run into any trouble.

**Comment by martinklepsch** [comment]
Closing this in favor of #30
