### ISSUE TITLE
Documentation missing/unclear: "Creating Externs"

### ISSUE THREAD

**Issue by mathpunk** [cljsjs/packages#261]
I was following the [Creating Packages](https://github.com/cljsjs/packages/wiki/Creating-Packages) instructions, which link to the [Creating Externs](https://github.com/cljsjs/packages/wiki/Creating-Externs). That page explains very well what externs _are_, but not how to create them. Instead, it links to an online tool for generating externs, which asks for a URL (of a github repo? of a url? of a file? who knows?) and for a JavaScript object to package.

Specifically, I'd like to package [Snap.svg](https://github.com/adobe-webplatform/Snap.svg) but I don't know what source URL to link, nor which object should be packaged.

**Comment by martinklepsch** [comment]
Hey Tom. If you understand what externs are for it should become pretty apparent how they need to look. Basically during advanced compilation the Closure compiler renames all variables unless they're listed in externs. This allows you to use external scripts in your code without the functions you're calling/variables you're using being renamed. (Renaming would cause things to break.)

Take a look at some of the externs of other projects and you should get a good idea what's needed.

Hope this helps

**Comment by martinklepsch** [comment]
As for the generator: try this one: http://jmmk.github.io/javascript-externs-generator/

As source file use https://github.com/adobe-webplatform/Snap.svg/raw/master/dist/snap.svg-min.js

As object to export try `Snap`. I'm not sure if this will be sufficient the API docs give me the impression that there are multiple global vars exported by the library.

**Comment by mathpunk** [comment]
> If you understand what externs are for it should become pretty apparent how they need to look. 

Sure, but knowing what they need to look like is different than doing whatever it is that people do to extract that information -- regular expressions? AST parsing? awk? (I hope it's not awk.)

Your recommended values have created output, at least -- I will experiment and find out if something is missing. All global vars need to be externed, then?
