### ISSUE TITLE
React 0.14 package incomplete

### ISSUE THREAD

**Issue by swannodette** [cljsjs/packages#263]
It does not include the second required ReactDOM script and thus spews errors.

See, https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by martinklepsch** [comment]
It's already there: https://github.com/cljsjs/packages/tree/master/react-dom 

React does not explicitly depend on ReactDom so you need to depend on it yourself.

**Comment by swannodette** [comment]
Ah great! Closing. Thanks.
