### ISSUE TITLE
Request: HUSL Colors

### ISSUE THREAD

**Issue by den1k** [cljsjs/packages#271]
[HUSL](http://www.husl-colors.org/) provides the human friendliest colorspace I know. Would love to have it as a dep in CLJS.

**Comment by Deraen** [comment]
Seeing that the implementation is only 300 lines (https://github.com/husl-colors/husl/blob/master/husl.coffee), you could very easily just re implement it in Clojure. It could be crossplatform for Clojure and ClojureScript and you wouldn't need a wrapper.

**Comment by den1k** [comment]
@Deraen there already is a Java port https://github.com/husl-colors/husl/blob/master/ports%2Fjava%2FHuslConverter.java

**Comment by Deraen** [comment]
Though I recommended re-implementation, a PR to add this package would be accepted.

**Comment by Deraen** [comment]
Merged.
