### ISSUE TITLE
How to package Closure libraries?

### ISSUE THREAD

**Issue by martinklepsch** [cljsjs/packages#28]
Follow-up on #23. @olivergeorge @jeluard

When Javascript libraries like [openlayers](https://github.com/openlayers/ol3) are written as Closure libraries it would be great to include them as such and profit from things like dead code elimination.

What is the best way to do this in the context of CLJSJS? Does `deps.cljs` support the packaging of Closure libs i.e. can it contain a `:libs` key similar to the one being passed to the Clojurescript compiler?

**Comment by olivergeorge** [comment]
Eric, [in the OL3 forum](https://groups.google.com/forum/#!searchin/ol3-dev/oliver/ol3-dev/TyhQqM-GlBM/oPOxVFIb3egJ), pointed to Google Closure features for matching namespaces to files.  I guess that's the familiar top level script when you build without optimisations.

> Namespaces (defined with good.provide) and file names are independent. You can even have files that goog.provide multiple namespaces. And you to have some script to create addDependency statements defining the dependencies tree and the matching between provided namespaces and files. This is what Closure Library's depswriter.py script does.

I guess that could provide the necessary mapping but that's speculation.  I'm sure David or one of the other compiler devs will be able to give some concrete advice.

**Comment by martinklepsch** [comment]
Ok. Pretty sure we can package this stuff as native Closure libs. I'll see if I can pull together an example.

**Comment by swannodette** [comment]
@olivergeorge for Closure libraries that follow classpath naming conventions there's nothing to do. For Closure libraries that do not there is the `:libs` features. I haven't used it so it needs to be verified that it hasn't regressed.

**Comment by martinklepsch** [comment]
So that was actually pretty straightforward. I put it together for openlayers in a [native-closure](https://github.com/cljsjs/packages/tree/native-closure) branch.

I

**Comment by martinklepsch** [comment]
Oh just in case that's not clear: packaging things like OpenLayers with `:libs` allows it to be used just like regular Closure libs/Clojurescript namespaces.

```clojure
(ns my.app
	(:require [ol.animation :as anim])
  (:import ol.Map ol.source.MapQuest))
```

**Comment by jeluard** [comment]
Great stuff!
So is it the ClojureScript compiler that does all the goog.provide -> filename conversion?

> move Closure libs into another repo (closure-libs) 
I do think it would be sufficient to specify this is a closure library in the readme. Not sure creating an extra repo is worth it.

**Comment by martinklepsch** [comment]
I also like the idea of splitting things up for the sake of discoverability but we can leave that for another day.

**Comment by olivergeorge** [comment]
Looks to have worked like a charm.  My [example](https://github.com/condense/example_openlayers_cljsjs/tree/master/hellool) file size is sane and it's working.

**Comment by olivergeorge** [comment]
What's the next step on this?  I'll use it in a current project so it would be nice if it was uploaded to clojars.

**Comment by martinklepsch** [comment]
@olivergeorge Uploading `3.1.1-1` right now. If you'd like to get `3.2` please update it via PR.

@olivergeorge @jeluard if anyone of you guys feels like helping with maintaining this I'm happy to add you as contributors. I'm planning to write up some `CONTRIBUTING.md` to make this easy peasy :sun_with_face:

**Comment by olivergeorge** [comment]
I'd be pleased to be a contributor and help out.  I think I'll be doing
plenty of cljs work this year.

**Comment by martinklepsch** [comment]
@olivergeorge added you to the @cljsjs/contributors group :)
I'm closing this now as the Closure question as been answered :)

**Comment by jeluard** [comment]
@martinklepsch Do you mind adding me as a contributor? I'd like to add some details to the README.

**Comment by martinklepsch** [comment]
@jeluard done/

**Comment by jeluard** [comment]
Thanks!
