### ISSUE TITLE
Codemirror package missing getDoc extern

### ISSUE THREAD

**Issue by continuata** [cljsjs/packages#284]
Calls to `(.getDoc editor)` are being replaced in production build minification and cause an exception.
The following should fix it
```js
/**
 * Get the document object.
 * @return {CodeMirrorDoc}
 */
CodeMirrorObj.prototype.getDoc = function(){};
```

**Comment by ohlo** [comment]
Well, it's missing more than that. I generated this file from the CodeMirror obj. But I guess there is a better way to generate that produces docs?
 
[codemirror-externs.txt](https://github.com/cljsjs/packages/files/45629/codemirror-externs.txt)

**Comment by ohlo** [comment]
answering my own question... the wiki has links to sites e.g. http://jmmk.github.io/javascript-externs-generator/ which could create the externs.

**Comment by Deraen** [comment]
Fixed in https://github.com/cljsjs/packages/commit/73f3478b6d87eb0d00f8315427728d5635a0b22e
