### ISSUE TITLE
Request JointJS

### ISSUE THREAD

**Issue by timur-han** [cljsjs/packages#334]
JointJS [1] is a modern HTML 5 JavaScript library for visualization and interaction with diagrams and graphs. It can be used to create either static diagrams or, and more importantly, fully interactive diagramming tools such as workflow editors, process management tools, IVR systems, API integrators, presentational applications and more. JointJS makes it easy to create visual tools of various kinds.

JointJS Core library is licensed under the Open Source Mozilla Public License Version 2.0. The JointJS Core library is everything you can download from the Download page. 

[1] http://www.jointjs.com/

**Comment by just-sultanov** [comment]
Hi!
This issue has been closed with the next PR # 1785.
I'm currently working on upgrading to the latest version (v3.0.4)
