### ISSUE TITLE
React-native externs

### ISSUE THREAD

**Issue by artemyarulin** [cljsjs/packages#338]
Hi, 

I've started working on React Native extern file which has some additional to normal React methods and props. Question - is it OK if I would create a package with only extern file? There is no way how I can include ReactNative source code as it's pretty much depends on the application (actually they have their own packager)

**Comment by Deraen** [comment]
Extern only is OK.

**Comment by artemyarulin** [comment]
Thanks!

**Comment by Deraen** [comment]
@artemyarulin Btw. have you spoken about with people who are using React-native? I don't know much about it myself but I remember reading that advanced compilation is not that useful with it? The software is probably downloaded once (per version) from app store or such so the file size is not that important.

**Comment by artemyarulin** [comment]
In short there are still benefits from it:

One of the advantages of React Native is hot release (= ability to deploy new version without AppStore review). Right now simple app (with om-next):

|Optimisation level |  Size     | Size (gzip best) |
|------------------------|----------- |-----------------------|
|`simple`                | 1.1MB   | 148KB                |
|`advanced`           | 169KB  | 43KB                  |

The difference would be bigger for the real app which includes different libraries, etc.  

Another reason for the advanced optimisation - it's really good obfuscator. With React Native all your source code is available in the app bundle and it's dramatically easy to replicate the app. With advanced optimisations it's much easier to write software from scratch rather than steal the source and try to go through all the garbage from Google Closure

**Comment by martinklepsch** [comment]
Would be cool to get a PR for this :+1:

**Comment by artemyarulin** [comment]
@martinklepsch Unfortunately I'm quite booked with another things to make a PR, but some time ago I've created https://github.com/artemyarulin/react-native-externs which is already released to the Clojars and using the same approach as in cljsjs - just add it as a dependency and it will work.

Feel free to take it and make a PR to cljsjs, just tell me then so I can edit a README and point users to the cljsjs version
