### ISSUE TITLE
Request: vis.js 4.11.0

### ISSUE THREAD

**Issue by jwr** [cljsjs/packages#342]
Versions 4.10 and 4.11 bring a number of fixes, particularly important for users of the Network module.

There are some new methods (for example setSelection), so it isn't just a version number bump, unfortunately.

**Comment by ducky427** [comment]
See my [PR](https://github.com/cljsjs/packages/pull/344)

**Comment by ducky427** [comment]
@Deraen just merged my PR. So v4.11.0 is up on clojars now.

**Comment by jwr** [comment]
Yay, thanks! Much appreciated!
