### ISSUE TITLE
How to use cljsjs packages for non-cljsjs-prepared packages?

### ISSUE THREAD

**Issue by devurandom** [cljsjs/packages#35]
I am currently using jayq, which is not prepared for cljsjs. However, I would like to use the cljsjs packaging approach anyway and manage the JavaScript needed for jayq using Lein. When specifying cljsjs/jquery as a dependency of my project, jayq cannot find it and I see `ReferenceError: jQuery is not defined` on the JavaScript console. How do I do it properly?

**Comment by martinklepsch** [comment]
@devurandom When `jayq` is not requiring `cljsjs.jquery` you have to do it yourself:
```clj
(ns application.core
  (:require cljsjs.jquery))
```
Foreign libs are required (somewhat) similar to how regular libs are.

**Comment by devurandom** [comment]
So if I `:require cljsjs.jquery`, the `jQuery` symbol will appear in the global JavaScript scope?

**Comment by martinklepsch** [comment]
@devurandom yes.

**Comment by martinklepsch** [comment]
@devurandom please make sure to close issues in the future if your problem has been resolved.
