### ISSUE TITLE
cljsjs.jquery not pulled in when adding cljsjs.highcharts?

### ISSUE THREAD

**Issue by john2x** [cljsjs/packages#352]
I have the following project.clj

```
(defproject myproject "0.1.0-SNAPSHOT"
:description "FIXME: write description"
:url "http://example.com/FIXME"
:license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
:dependencies [[org.clojure/clojure "1.7.0"]
                [org.clojure/clojurescript "1.7.170"]
                [cljsjs/highcharts "4.1.10-0"]]
:plugins [[lein-cljsbuild "1.1.2"]]
:source-paths ["src/clj"]
:cljsbuild {:builds [{:source-paths ["src/cljs"]
                        :compiler {:output-to "resources/public/cljs/main.js"
                                :output-dir "resources/public/cljs"
                                :main "myproject.core"}}]})
```

But when building the project and opening it in the browser, I get `Uncaught Error: Undefined nameToPath for cljsjs.jquery` in the console. `cljsjs.jquery` isn't included in `lein deps :tree` as well.

Adding `cljsjs/jquery` to the project.clj fixes the issue.

Shouldn't `cljsjs/jquery` be automatically pulled in as a dependency of `cljsjs/highcharts`?

**Comment by crisptrutski** [comment]
Looks like a packaging issue - `deps-cljs` only adds the namespace dependency, but a `(set-env! :dependencies ...)` entry is required to add the `cljsjs.jquery` JAR.

@martinklepsch maybe worth linting against these kinds of omissions in the build?

**Comment by crisptrutski** [comment]
By-the-by `4.2.0` is out, so contributions welcome :smile:

**Comment by crisptrutski** [comment]
It also looks like the jQuery dependency is removed in `4.2.0` :dancer:
