### ISSUE TITLE
Improve documentation related to deployment

### ISSUE THREAD

**Issue by jeluard** [cljsjs/packages#359]
Can someone remind me what command-line I should use to push a package?

**Comment by martinklepsch** [comment]
Some is covered here: https://github.com/cljsjs/packages/blob/master/CONTRIBUTING.md

For pushing to Clojars or similar use Boot's `push` task.

**Comment by jeluard** [comment]
Ah nice! I was confused because this [page](https://github.com/cljsjs/packages/wiki/Creating-Packages) does not mention the last part regarding deployment (btw the circleci link is dead).

So I understand simply committing the new version is sufficient and the continuous testing will perform the deployment to clojars?

**Comment by Deraen** [comment]
Yes.

**Comment by jeluard** [comment]
Great! Thanks.

**Comment by Deraen** [comment]
Looks like some packages fail to build currently but script doesn't correctly set exit status.
