### ISSUE TITLE
Missing release

### ISSUE THREAD

**Issue by danielsz** [cljsjs/packages#38]
*cljsjs/leaflet* seems to be missing from clojars.org.

```bash
org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact cljsjs:leaflet:jar:0.7.3-0 in clojars (http://clojars.org/repo/)
```
Thanks in advance.

**Comment by martinklepsch** [comment]
@pandeiro ping

**Comment by martinklepsch** [comment]
@danielsz deployed it, thanks for letting us know. :100:

**Comment by pandeiro** [comment]
Thanks Martin, I'm afk today. I'll make sure to deploy releases from here
on out.
