### ISSUE TITLE
crypto-js sorely needed

### ISSUE THREAD

**Issue by jeaye** [cljsjs/packages#385]
To help with clojurescript's state of crypto support, it would be a great start to get https://github.com/brix/crypto-js into cljsjs packages.

**Comment by fredZen** [comment]
In the hope that this can help some future readers: cljsjs does have a package for Forge, which covers some of the same ground as crypto-js.

https://github.com/cljsjs/packages/tree/master/forge

**Comment by thachmai** [comment]
#1372 submitted for crypto-js 3.1.9-1
