### ISSUE TITLE
[react-with-addons] react-with-addons.inc.js not included

### ISSUE THREAD

**Issue by futuro** [cljsjs/packages#390]
Including react-with-addons brings in react.inc.js instead of react-with-addons.inc.js.

As a test, I rebuilt react-with-addons, changing the `(deps-cljs :name "cljsjs.react")` to `(deps-cljs :name "cljsjs.react-with-addons")` inside the build.boot package-with-addons function. I then did `boot package-with-addons pom jar install` and got both react.inc.js and react-with-addons.inc.js.

I don't know anything, really, about how packages work in clojurescript, so if there's something I've missed, please let me know.

**Comment by Deraen** [comment]
React with addons is by design packaged as `cljsjs.react` namespace so that user can replace React dependency on libraries by replacing react with react-with-addons dependency.

You don't want both react.inc.js and react-with-addons.inc.js in your project because the latter replaces first.

**Comment by futuro** [comment]
Yeah, the problem I'm having is that when react-with-addons provides
cljsjs.react, lein (or whatever is pulling in dependencies) brings in
react.inc.js, not react-with-addons.inc.js, so it's as though I'm still
declaring a dependency on cljsjs.react.

**Comment by Deraen** [comment]
You probably have transitive dependency on cljsjs/react from Reagent/Om/Sablono or such. Check `lein deps :tree` and use `:exclusions` to filter out unnecessary transitive dependencies.

**Comment by ducky427** [comment]
@futuro, have a look at [this](https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L45) project.clj on how to exclude dependencies.

**Comment by futuro** [comment]
@Deraen @ducky427 Thanks, that did it!

I'm not certain if this issue comes up a lot, but would you all be interested in a note in the README? Do boot users need to declare exclusions for transitive dependencies?

**Comment by Deraen** [comment]
PR to improve readme or document in wiki would definitely be welcome.

**Comment by futuro** [comment]
PR #394 created.
