### ISSUE TITLE
dom-delegator

### ISSUE THREAD

**Issue by fehrenbach** [cljsjs/packages#408]
It would be nice to have a package for [dom-delegator](https://github.com/Raynos/dom-delegator). The virtual-dom package apparently needs this around at runtime for event handling to work.

There is not much of a public API, so an externs file is probably easy.
However, it does not seem to have a single js file available for download.
I managed to create something that seems to work with `npm install dom-delegator && browserify -r dom-delegator/index.js:delegator -s Delegator -o dom-delegator.js` but I don't  know if this is a sensible approach to compiling npm modules.

**Comment by martinklepsch** [comment]
@fehrenbach I since most builds are done on CI now we can safely shell out and do some `npm` stuff if needed. See [blockapps](https://github.com/cljsjs/packages/blob/d1cbb8a9be1d6737028ede59522323f2a4585ca8/blockapps/build.boot) as an example.

**Comment by fehrenbach** [comment]
I tried, but there is too much boot stuff I don't understand. If anyone has the boot know-how, please go ahead.

I *think* you just want to download a tar ball && untar && cd, `npm install` (for dependencies), `npm install browserify`, `./node_modules/.bin/browserify -r ./index.js -s Delegator -o dom-delegator.inc.js`.

The externs file should look like this:
```js
/** @constructor */
function Delegator() {}

Delegator.prototype.allocateHandle = function () {};
Delegator.prototype.transformHandle = function () {};
```

And the whole thing should result in a single top-level constructor to be called like this: `(js/Delegator.)`.
