### ISSUE TITLE
Is it possible to update the version of a package?

### ISSUE THREAD

**Issue by sp3ctum** [cljsjs/packages#430]
Hi guys, loving the project a lot!

I'm using the react-select package in my cljs app. It's working fine, except the react-select library has a bug that manifests in my use case. I see the bug should be fixed in a newer version:

https://github.com/JedWatson/react-select/issues/648

But it looks like the version included by `cljsjs` has been compiled too early for that fix to make it in. This page states the version has been compiled December 26th:

https://clojars.org/cljsjs/react-select

Is there a policy about updating cljsjs packages in these cases? Thanks!

**Comment by Deraen** [comment]
The preferred way to update a package is to create a pull request.

We have no written policy, but maybe that's something we should create.

**Comment by sp3ctum** [comment]
Great, I created one here: https://github.com/cljsjs/packages/pull/431

I haven't viewed testing policies yet though. What should I test?

**Comment by sp3ctum** [comment]
Another go at the pull request here: https://github.com/cljsjs/packages/pull/432

**Comment by Deraen** [comment]
I added mention about using latest commit for PRs on https://github.com/cljsjs/packages/blob/master/CONTRIBUTING.md.

It also includes the command to test the packaging task. It will install the library to local Maven repo so that one can test the library in other project (e.g. real project using the lib).

**Comment by sp3ctum** [comment]
That sounds great :+1: 

After the update, the bug I mentioned earlier is gone in my app. Thanks a lot!
