### ISSUE TITLE
Request: Animate.css

### ISSUE THREAD

**Issue by flyboarder** [cljsjs/packages#435]
Animate.css
https://daneden.github.io/animate.css/

**Comment by Shearerbeard** [comment]
I also need this so I'll add a package for this and submit a PR a bit later unless someone is already working on it.

**Comment by flyboarder** [comment]
I didn't start on one yet, created the issue as a reminder.

**Comment by Shearerbeard** [comment]
Just submitted the package in PR #449.

**Comment by flyboarder** [comment]
closing as per #449
