### ISSUE TITLE
Add https://github.com/bitwiseshiftleft/sjcl/

### ISSUE THREAD

**Issue by xcthulhu** [cljsjs/packages#456]
The *Stanford JavaScript Crypto Library* would make an excellent addition to the libraries provided by CLJSJS.

The barrier I see to just rolling this out quickly is that the maintainers do not provide an unminified version of their code on their repo; users are expected to compile it themselves:

https://github.com/bitwiseshiftleft/sjcl/issues/207

Does this mean CLJSJS isn't interested in supporting it?

**Comment by Deraen** [comment]
You can run the build as part of package task, like here: https://github.com/cljsjs/packages/blob/f1c11bd493fd25d30b124f976f295c5e43c2cbfa/react-mdl/build.boot#L22-L34

Also, I don't think it's a problem if you only include minified file.

**Comment by xcthulhu** [comment]
Okay, I'll go ahead and make a PR

**Comment by xcthulhu** [comment]
I've been investigating the issue of including an unminified version, and I raised it up over at SJCL:

https://github.com/bitwiseshiftleft/sjcl/issues/279

What I've found is that they essentially cannot make a viable *unminified* version of their library, as you can see from their custom build script:
https://github.com/bitwiseshiftleft/sjcl/blob/master/compress/compress_with_closure.sh#L32

I've made my own package for SJCL with a custom build, I'm not going to hoist this on CLJSJS:

https://github.com/xcthulhu/sjcl-cljs/commits?author=xcthulhu
