### ISSUE TITLE
Use gh-pages to publish packages + versions

### ISSUE THREAD

**Issue by pandeiro** [cljsjs/packages#47]
It would be great for ClojureScript users to have a quick visual reference to the JS libraries available as CLJSJS packages. Currently, this involves clicking through this repository's already sizeable directory structure and knowing where this information resides in the `build.boot` files (many are not Boot users yet), making discoverability less than ideal.

A script and/or ClojureScript application to produce a static HTML page with up-to-date information would potentially solve these problems if CLJSJS members who commit and push releases rebuild the index after doing so. Furthermore this could be served for free using Github Pages, and additionally linked to or embedded (via iframe) in the main CLJSJS organization's Github page.

I've already come up with a working implementation of part of this locally and would be happy to create a branch for this here, if there's interest. Beforehand, I'd like to see what others thoughts are regarding this approach.

**Comment by martinklepsch** [comment]
Sounds awesome, lets do it! :)
(There is some static site in the cljsjs.github.io repo already btw)

On Friday, February 20, 2015, Murphy McMahon <notifications@github.com>
wrote:

> It would be great for ClojureScript users to have a quick visual reference
> to the JS libraries available as CLJSJS packages. Currently, this involves
> clicking through the repository's directory structure and knowing where
> this information resides in the build.boot files (many are not Boot users
> yet), making it less than ideal.
>
> A script and/or ClojureScript application to produce a static HTML page
> with up-to-date information would potentially solve these problems if
> CLJSJS members who commit and push releases rebuild the index after doing
> so. Furthermore this could be served for free using Github Pages, and
> additionally linked to or embedded (via iframe) in the main CLJSJS
> organization's Github page.
>
> I've already come up with a working implementation of part of this locally
> and would be happy to create a branch for this here, if there's interest.
> Beforehand, I'd like to see what others thoughts are regarding this
> approach.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cljsjs/packages/issues/47>.
>


-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>

**Comment by pandeiro** [comment]
Cool @martinklepsch! I'm gonna create an issue-47 branch to show what I've got so far and we can take it from there.

**Comment by martinklepsch** [comment]
@pandeiro @Deraen There now is a version of that on http://cljsjs.github.io — should we close this?

**Comment by Deraen** [comment]
Yeah I think this can be closed.

**Comment by pandeiro** [comment]
Yep, great work on that btw! :+1:
