### ISSUE TITLE
React v15.0 Release Candidate 2 is out

### ISSUE THREAD

**Issue by kanwei** [cljsjs/packages#475]
Are these supposed to be updated automatically?

https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html

**Comment by Deraen** [comment]
Nope, updates require manual update to packaging files: https://github.com/cljsjs/packages/commit/63dfa2fd59fd65c7ef05e1ca89ea3b76530d1d31

Packages will be available in few minutes.
