### ISSUE TITLE
Use library tagline for pom descriptions

### ISSUE THREAD

**Issue by pandeiro** [cljsjs/packages#49]
It would be less ambiguous to use JS library's tagline/descriptions in this field, rather than the "X library packaged with Closure externs" -- both because it identifies the package better and removes doubt about a package that doesn't mention externs (the inclusion of which should be a given if it is a cljsjs package).

**Comment by Deraen** [comment]
Sounds a good idea

**Comment by Deraen** [comment]
Great! In future we'll hopefully be able to show these on gh-pages after clojars get a proper API.
