### ISSUE TITLE
strategy for lib+addons pattern?

### ISSUE THREAD

**Issue by shaunlebron** [cljsjs/packages#50]
I have been at a loss for packaging libraries with optional addons.  For example:

- [Flot](http://www.flotcharts.org/) - core + [14 optional plugins](https://github.com/flot/flot/search?utf8=%E2%9C%93&q=filename%3Ajquery.flot.*.js+path%3A%2F&type=Code)
- [Highlight.js](https://highlightjs.org/) - core + [116 optional languages](https://github.com/isagalaev/highlight.js/tree/master/src/languages)

Users are expected to include the individual JS files to enable their respective addons.  This is to reduce file size, of course.

I saw the [React+addons](https://github.com/cljsjs/packages/blob/9fa993a5511c7ba436e4a44cdbe8258138b511d0/react/build.boot#L25-L41) solution in this repo, but this type of solution wouldn't work for multiple combinations of addons.

Ideally, the solution would be to include all addons and have Google Closure eliminate the dead code for you.  But obviously, this isn't a general solution for non-closure libraries.

Any ideas?

**Comment by swannodette** [comment]
React+addons is actually not ideal as the addons are not supplied separately. The libraries you've mentioned are far easier to support. You can define as many entries in `:foreign-libs` as you want in your package and can describe any dependencies via `:requires`.

**Comment by martinklepsch** [comment]
This has been done for moment.js locale files: https://github.com/cljsjs/packages/blob/master/moment/build.boot

I'm pretty sure something similar can be done for the libraries you mentioned.
And as @swannodette mentioned React and it's add-ons are a different kind of problem.

**Comment by shaunlebron** [comment]
Oh wow, that's awesome.  I'll start working on the PRs.  Thanks
