### ISSUE TITLE
Add node.js version of https://github.com/dcodeIO/bytebuffer.js

### ISSUE THREAD

**Issue by moxaj** [cljsjs/packages#505]
Available at https://raw.githubusercontent.com/dcodeIO/ByteBuffer.js/master/dist/bytebuffer-node.js. I reckon the externs could stay the same. Thanks!

**Comment by Deraen** [comment]
I guess with Node.js it is easiest to just use npm packages. Externs are not required there anyway as advacned is unncessary with Node.
