### ISSUE TITLE
Incorrect hammer.js is packaged

### ISSUE THREAD

**Issue by jeluard** [cljsjs/packages#52]
When using `cljsjs-hammer` in development I get weird JS errors. It looks like the wrong `hammer.js` file is packaged, not the aggregated one but [this one](https://github.com/hammerjs/hammer.js/blob/master/src/hammer.js).

**Comment by martinklepsch** [comment]
Fixed in `[cljsjs/hammer "2.0.4-3"]`

**Comment by jeluard** [comment]
Thanks it works perfect now!
