### ISSUE TITLE
Externs for react-chartjs?

### ISSUE THREAD

**Issue by jarcane** [cljsjs/packages#534]
I've been having a stab at trying to create a package for [react-chartjs](https://github.com/jhudson8/react-chartjs), but I've rather hit an impasse. I've a [forked branch](https://github.com/cljsjs/packages/compare/master...jarcane:react-chartjs) started, but the externs file is still empty because I'm basically at a complete loss as to how to generate externs for the library, as it's structured in such a way there doesn't seem to be any single object to point the extern generator at.

Perhaps I'm simply missing something here, or is this not possible? It being a CommonJS component itself doesn't seem to pose a barrier as others have done CLJSJS packages from those (I based the build script for instance on reactabular), but in that case there was still a Reactabular object someone could point the extern generator to.

Any ideas?

**Comment by Deraen** [comment]
I think we came to conclusion to not use React-chartjs and just directly wrap ChartJS in Reagent components?

**Comment by jarcane** [comment]
Yes. It actually turned out as well that react-chartjs binds to an outdated version as well, so even without the externs problem, it's probably not worth the effort to get it running. In the end I wound up just using Chartjs directly.
