### ISSUE TITLE
Hammer.js refers to non existing source map file

### ISSUE THREAD

**Issue by jeluard** [cljsjs/packages#56]
In advanced mode the hammer.js file that ends up being packaged refers to a non existing source map file.

It is an issue as the source map file does not exist and its relative path is hardcoded. Even so it was successfully resolved by your web server I believe it would break anyway as line offset would be wrong (see some related [nodejs tool](https://github.com/thlorenz/combine-source-map)).
Finally this is probably something we want to have configurable.

For now I would suggest to just strip source map references from js files.

**Comment by martinklepsch** [comment]
> For now I would suggest to just strip source map references from js files.
Only minified files have those references right? If so that sounds right to me.

I suggest we add that as a task to the `cljsjs.boot-cljsjs.packaging` namespace:
https://github.com/cljsjs/boot-cljsjs/blob/master/src/cljsjs/boot_cljsjs/packaging.clj

@jeluard would you be up to do that?

**Comment by jeluard** [comment]
Sure I will take a look at that.

**Comment by jeluard** [comment]
I just pushed a more general `replace-content` task that can be used to strip unneeded source map references. See [boot-cljsjs#22](https://github.com/cljsjs/boot-cljsjs/pull/22).

Let me know what you think!

**Comment by jeluard** [comment]
Oups didn't realized I wasn't on my fork sorry.. Plus I mistakenly changed the regexp..

**Comment by jeluard** [comment]
How can I get the right to push to clojars?

**Comment by martinklepsch** [comment]
I can add you - what's your username?

**Comment by jeluard** [comment]
It's `julien`.

**Comment by martinklepsch** [comment]
Added you :)

**Comment by jeluard** [comment]
Great it worked fine! Thanks!
