### ISSUE TITLE
Auth0 and Auth0 Lock libraries need upgrade for security

### ISSUE THREAD

**Issue by tel** [cljsjs/packages#577]
An email sent out tonight from Auth0 warns that 

> If your apps reference a specific Lock or auth0.js version (e.g. lock-6.8.1.js) or if you bundle the libraries yourself, then you must update your code to use at least these versions:
>
> If you use Lock: Lock versions: 9.1.4, 8.3.2 or 7.14.3 (we recommend 9.1.4)
> If you use the auth0.js library: auth0.js version: 6.8.3

Cljsjs bundles versions 8.1.5 and 6.3.0 respectively and they should be updated. Some functionality may be disabled for some users of these libraries as early as 3pm PST tomorrow.

Full text of security report email below

---

We have discovered and patched a serious vulnerability in the JSONP endpoint https://{YOUR ACCOUNT}.auth0.com/user/ssodata used by the Auth0 Lock and auth0.js libraries. This endpoint supports JSONP for browser backward compatibility. If users that are logged in to your website also browse a malicious website, their email and user_id could be disclosed. This could happen only if users are still logged in to your app and they still have the Auth0 SSO cookie.

If your JavaScript apps reference the versions below, no action is required as the update will be applied automatically:

lock.js: 10.x, 9.1, 8.3 or 7.14
auth0.js: 6.8
Note that this security update is necessary solely for web applications. It doesn’t apply to native apps on iOS, Android or Windows Phone.

## Applying the Security Update

Please examine the JavaScript in your client and follow these instructions:

### Automatic Update

The update will be automatically applied and no action is required if you reference Lock or auth0.js with this code without specifying the PATCH number. For example:

<script src="https://cdn.auth0.com/js/lock-9.1.min.js"></script>

<script src="https://cdn.auth0.com/w2/auth0-6.8.min.js"></script>

### Manual Update

If your apps reference a specific Lock or auth0.js version (e.g. lock-6.8.1.js) or if you bundle the libraries yourself, then you must update your code to use at least these versions:

If you use Lock: Lock versions: 9.1.4, 8.3.2 or 7.14.3 (we recommend 9.1.4)
If you use the auth0.js library: auth0.js version: 6.8.3
You may update simply by replacing the current reference to Lock with as an example:

    <script src="https://cdn.auth0.com/js/lock-9.1.min.js"></script>

Or auth0.js:

    <script src="https://cdn.auth0.com/w2/auth0-6.8.min.js"></script>

## What changes, why and when?

Effective 3:00pm Seattle time (PT) tomorrow (Thursday May 12th, 22:00 UTC), we are deprecating (and disabling) JSONP support for the .getSSOData method in these libraries. Most apps will not be affected by this change of disabling the JSONP endpoint. If they are, it will be because the call will always return this result, which might not reflect accurately the actual user state:

    {
      "sso": false
    }

This means that users will likely have to enter credentials again when navigating from one website to another, and not experience SSO. We do not expect users of apps that are affected to see any other changes in behavior.

The JSONP primary use case was to support older browsers with incomplete or poor CORS support (e.g. Internet Explorer <= version 9). We have become aware that supporting JSONP creates a security vulnerability.

Security and privacy are of paramount importance to us. We make changes quickly like this only when we believe it is absolutely necessary to protect you and your users. We strongly recommend you update your libraries ASAP.

If you feel you cannot make these changes by tomorrow’s deadline, please click here to request postponing the deprecation for your account for an additional two weeks. Please bear in mind that we strongly recommend no delay in this security update.

If you need help fixing this, you can open a ticket in our Support Center or join our Discussion Forum.

Thanks!

The Auth0 Support Team - https://auth0.com

**Comment by Deraen** [comment]
Merged.
