### ISSUE TITLE
request: dimplejs

### ISSUE THREAD

**Issue by danielneal** [cljsjs/packages#58]
DimpleJS is a pretty neat charting library that uses d3 under the hood. 
http://dimplejs.org/

**Comment by danielneal** [comment]
So, I've made a start on this:
https://github.com/danielneal/packages/tree/master/dimple

But when I try and use it in a project, I get a heap of errors:

    dimple requires d3 to run.  Are you missing a reference to the d3 library?
    d3.inc.js:1 Uncaught SyntaxError: Unexpected reserved word
    chart.js:6 Uncaught ReferenceError: dimple is not defined

Any ideas? I'm still wrapping my head around `cljsj` (and `boot`)..

**Comment by danielneal** [comment]
So I got dimple to work :)
I had to make a slight change to the d3 package. 
The `sift` task was overwriting the full `d3.js` with a `d3.js` which just had a bunch of import stubs. 

Details here: 
https://github.com/danielneal/packages/tree/dimple

**Comment by martinklepsch** [comment]
> I had to make a slight change to the d3 package. The sift task was overwriting the full d3.js with a d3.js which just had a bunch of import stubs.

Is that still the case with the current version of D3 in this repo? PR to fix it here would be very welcome!

I had a quick look at your branch and it looks ok. Feel free to open a PR for further feedback :)

**Comment by danielneal** [comment]
Thanks, yep that's still the case with current D3...
The PR I just submitted adds dimple and makes the fix.
