### ISSUE TITLE
AWS SDK produces failing build under `optimizations: advanced`

### ISSUE THREAD

**Issue by den1k** [cljsjs/packages#601]
Project reproducing the failure:

https://github.com/den1k/gclosure-aws-test
## Reproduce failure under advanced optimizations

```
lein figwheel ;; serve index
```

Once figwheel is live http://localhost:3449/
overwrite the compiled ClojureScript with the advanced build.
**Warning:** Don't make any changes to the code or figwheel will
 overwrite the build.

```
rm -rf resources/public/js/compiled && lein cljsbuild once min
```

Refresh the page. It should break. See debugging console.

**Comment by ducky427** [comment]
There is a good chance that the externs aren't complete. For example, `getObject` and `listObjects` are most likely missing from `AWS.S3`.

**Comment by OscarMarshall** [comment]
They're not complete. The whole SES service is missing.

**Comment by Deraen** [comment]
https://github.com/cljsjs/packages/commit/d7b31fd03c19cb255bc90fc973b68b780d6ea681
