### ISSUE TITLE
Update Plottable

### ISSUE THREAD

**Issue by levitanong** [cljsjs/packages#636]
Latest release: https://github.com/palantir/plottable/tree/v2.2.0

I've been trying to update this, but I keep getting a `No .inc.js file found!` error. Maybe someone with more experience will be able to pull this off.

**Comment by ducky427** [comment]
@levitanong, I see that `plottable.js` and `plottable.min.js` both are packaged nicely in the repo. So if you were to update the version number in the `plottable/build.boot` and the checksum, it should probably work. Obviously this is assuming that the API hasn't changed. If it has, you'll need to update the externs as well.

Have a look at this [document](https://github.com/cljsjs/packages/wiki/Updating-packages).

**Comment by levitanong** [comment]
I'm successfully getting the zip and all the necessary files are present in the zip. 
However, when I do a `(show :fileset true)` after `(sift :move ...)`, none of the `.inc.js` files are there. Any hints, @ducky427?

**Comment by ducky427** [comment]
It could be that the package you are downloading is getting unzipped to a different directory than what's assumed in the `(sift :move ...)`. And so the function isn't doing what is expected.

**Comment by levitanong** [comment]
@ducky427 So the filename of the zip file is different from that of the URL. 
The URL, taken from github is:
`https://github.com/palantir/plottable/archive/v2.2.0.zip`

But once downloaded, the filename is:
`plottable-2.2.0.zip`.

Could this be the issue?

**Comment by ducky427** [comment]
It is. Now the unzip folder is `plottable-2.2.0`. You should add this pattern to the filename regexes.

**Comment by levitanong** [comment]
omg it worked! You're a lifesaver, @ducky427!

**Comment by ducky427** [comment]
awesome! np.
