### ISSUE TITLE
New Version for https://github.com/ecomfe/echarts 3.2.2

### ISSUE THREAD

**Issue by apterf** [cljsjs/packages#647]
There is a new version for [echart(3.2.2)](https://github.com/ecomfe/echarts).
The current build in cljsjs is 2.2.7

Could you please help to update it ;)

**Comment by ducky427** [comment]
@apterf, why don't you give it a go. There is the [doc](https://github.com/cljsjs/packages/wiki/Updating-packages) for updating a package.

I'll help you if you get stuck.

**Comment by Deraen** [comment]
Closing as there is already a PR: #654
