### ISSUE TITLE
React-dom params trigger :check-types errors

### ISSUE THREAD

**Issue by nha** [cljsjs/packages#658]
I recently added compile-time checking in my project (as described there: https://github.com/clojure/clojurescript/wiki/Compile-Time-Type-Checking ).

This triggers errors like this one:

```
SEVERE: file:/Users/nha/.m2/repository/cljsjs/react-dom/15.0.1-1/react-dom-15.0.1-1.jar!/cljsjs/react-dom/common/react-dom.ext.js:29: ERROR - Bad type annotation. missing opening (
 * @param {function=} callback
```

Fromt this line: https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/react-dom/common/react-dom.ext.js#L29

My understanding after reading the doc ( https://developers.google.com/closure/compiler/docs/js-for-compiler#types ) is that `Function=` is intended to mean an optional function.

However it does not seem to be valid (not sure why yet) ?

So is it a syntax error, or should it be replaced by ClojureScript IFn ( https://github.com/clojure/clojurescript/blob/0fcbef2bf6be543ce72de4797701fdd55b332922/src/main/cljs/cljs/core.cljs#L441 ) protocol ? If a change is needed, would a PR be welcome ?

**Comment by ducky427** [comment]
@nha, could you share a simple project demonstrating this?

**Comment by ducky427** [comment]
I think the change should be replacing `Function=` with `function()=` but need to check.

**Comment by nha** [comment]
Well that does not seems to do it for me. I will make a simple reproduction (I use boot-cljs but I really think that all that is needed is to enable this compiler option, that not a lot of people seem to use).

**Comment by Deraen** [comment]
https://github.com/cljsjs/packages/commit/b497a1f75159212015d3b72f25b6e9a38daf5e62
