### ISSUE TITLE
Documentation vs Boot Task is inconsistent

### ISSUE THREAD

**Issue by flyboarder** [cljsjs/packages#659]
In the wiki the folder structure which is documented is not how the `from-cljsjs` task is coded. Folders following the wiki structure will not be found during unpack.

https://github.com/cljsjs/boot-cljsjs/blob/master/src/cljsjs/boot_cljsjs.clj#L35

The above line will not find folders which look like `cljsjs/<project>/<common|development|production>` instead they match `cljsjs/<common|development|production>/<project>`

A few packages have this issue.

**Comment by Deraen** [comment]
https://github.com/cljsjs/boot-cljsjs/issues/10

**Comment by Deraen** [comment]
`from-cljsjs` and other similar tasks have been removed in boot-cljsjs master, this will be included in the next release.
