### ISSUE TITLE
Facebook fixed-data-table

### ISSUE THREAD

**Issue by olivergeorge** [cljsjs/packages#67]
Hi @ghedamat, Hi @pandeiro

I'm trying to package Facebook's FixedDataTable component.  Hoping you can help me along based on your recent experience with ReactRouter.

https://github.com/cljsjs/packages/tree/fixed-data-table

I'm having trouble getting it going.  I'm not sure how to generate the externs and what initialisation is needed (webpack related possibly).  I had a brief attempt at http://www.dotnetwise.com/Code/Externs/ but no joy.

When I include my packaged version in a clean "lein new mies-om" and (:require) it I get a JS error in the browser which makes me think the JS file isn't initialising correctly and, ultimately, no js/FixedDataTable is available.

Can you give me some tips please.

thanks, Oliver

**Comment by pandeiro** [comment]
Hi @olivergeorge,

So I took a quick look and once again, similar to my experience with ReactRouter, I don't get how to load this library.

So far, all I've done is test trying to load it into the Externs generator and build externs for the FixedDataTable object. But that object, which should be global from my understanding, couldn't be found.

I'll circle back and try again but in the meantime, are there any channels we can use to check with the authors if loading straight in a script tag is even possible?

**Comment by pandeiro** [comment]
Ahhh, now I remember: I think we need to first 1) load react in the externs generator, then 2) the fixed-data-table, and then 3) try to extract the externs for the FixedDataTable object. See if that works?

**Comment by ghedamat** [comment]
hi @olivergeorge sorry for the terrible delay, havn't had much open source time lately :/

If I recall correctly what @pandeiro is suggesting is exactly what we did
https://github.com/cljsjs/packages/blob/master/react-router/resources/cljsjs/react_router/common/react-router.ext.js#L1-L4

hope this helps!

**Comment by olivergeorge** [comment]
Thanks guys.

**Comment by olivergeorge** [comment]
To summarise the component required an ES6 feature Object.assign which meant a polyfill was required to get this to work.
