### ISSUE TITLE
Transitive cljsjs dependencies failing to resolve in some Leiningen tasks

### ISSUE THREAD

**Issue by worrel** [cljsjs/packages#686]
I've found an issue where cljsjs libraries that themselves depend on other cljsjs libraries break (some) non-CLJS Leiningen tasks.

I have a CLJS project that includes the `cljsjs/react-burger-menu` library, which in turn depends on `cljsjs/react` and `cljsjs/snapsvg`.  I also used Garden to generate CSS via `lein-garden`.  

Running `lein garden once` fails with `Could not find artifact cljsjs:snapsvg:jar:0.4.1-0 in central (http://repo.maven.apache.org/maven2)`.  Removing the `cljsjs/react-burger-menu` dependency fixes the issue.  Note it's not unique to this dependency, I also tried `cljsjs/react-bootstrap-datetimepicker` which depends on `cljsjs/momentjs` and `cljsjs/react-bootstrap` and reproduced the failure.

I believe the cause is the POM file generated for cljsjs libraries doesn't include the clojars repo.  At least, manually editing the `cljsjs/react-burger-menu` POM to add the <repository> element for clojars fixes the issue for me.  However, it's not like the dependency tree is unresolvable, running `lein deps :tree` prints the correct dependency tree without error, so perhaps the fault lies within the individual lein task implementation?

A workaround is to explicitly exclude the failing transitive cljsjs dependencies & then explicitly depend on them, which is a bit ugly.

Could we enhance cljsjs to simply include the clojar repo in each generated POM file? I believe that's a near-zero impact change that won't require tracking down code issues in lein plugins.

**Comment by Deraen** [comment]
We can't do much here (at least easily) about the pom.xml files as they are written by Boot. But I find the problem interesting, I checked lein-garden and it should be only doing very basic `eval-in-project`.

**Comment by Deraen** [comment]
Okay, found the cause and send PR to lein-garden as it will take some to fix this in Boot: https://github.com/noprompt/lein-garden/pull/46

**Comment by micha** [comment]
I'm not sure it's legit for a dependency, especially a transitive one, to bring in a Maven repository that the user has not added themselves.

**Comment by worrel** [comment]
I think it's legit to have the repo in the generated POM for cljsjs packages if they have dependencies that are only resolvable in that repo.  

Per the [POM reference](https://maven.apache.org/pom.html#Repositories) `Whenever a project has a dependency upon an artifact, Maven will first attempt to use a local copy of the specified artifact. If that artifact does not exist in the local repository, it will then attempt to download from a remote repository. The repository elements within a POM specify those alternate repositories to search.`

If we're generating cljsjs POMs that depend on other cljsjs artifacts & we know we're not pushing cljsjs artifacts to Maven central, it seems like we're knowingly creating broken POMs - or at least creating an undue burden on package users to add new repos.  I guess this wouldn't be so bad if clojars wasn't the de-facto "central" for Clojure & seems to be searched by default by most tools in the ecosystem.

**Comment by micha** [comment]
Thanks for the link! The part I'm unsure about is this:

> Whenever a **project** has a dependency upon an artifact...

and

> The repository elements within a POM specify those alternate repositories...

Since in the Maven world the pom is used as the build specification as well as the package description, it's not clear to me that that applies transitively.

Sorry if I'm being dense :)

**Comment by micha** [comment]
Like for example, the `<plugins>` are not loaded transitively, of course, but they're in the POM.

**Comment by micha** [comment]
I guess we can make a test. Does `mvn` add repositories to the build via `<repositories>` elements in the poms of transitive dependencies? I just assumed no, but maybe it does?

**Comment by Deraen** [comment]
Should be solved on lein-garden `0.3.0`: https://github.com/noprompt/lein-garden/pull/46
