### ISSUE TITLE
cljsjs/react-with-addons 15.1 -> 15.2 creates warnings for unknown props

### ISSUE THREAD

**Issue by mattsfrey** [cljsjs/packages#690]
The update from 15.1 to 15.2 changed something to the effect that if you now pass props to root level markup components, i.e. [:div..] react throws large stack trace warnings about them. 

This is a major problem as so many components use & args  and (into :div ...) when wrapping root level components, which will propagate all args downwards to the root level component which now throws this heavily obnoxious warning.

![screen shot 2016-08-08 at 2 15 57 pm](https://cloud.githubusercontent.com/assets/2801653/17494726/3f0fee64-5d73-11e6-9e41-913017c77375.png)

Guessing this came from the react update itself, but wondering if there is anyway to address it? These are very common patterns in cljs and will make writing abstract components much harder, and creates a huge PITA for existing code bases that have heavily employed them.

**Comment by ducky427** [comment]
not sure if this can be addressed here. This library is supposed to be unadulterated react library. Better to raise this with the cljs react wrapper of your choice.

**Comment by mattsfrey** [comment]
@ducky427 Thanks for the reply, I did indeed take it to react, and apparently in future versions they intend to just stuff whatever is passed to root components into the dom, which we definitely wouldn't want. It seems refactoring our components will have to be done at some point as painful as it may be.
