### ISSUE TITLE
error using highchart lib under advanced compilation

### ISSUE THREAD

**Issue by chihyangscience** [cljsjs/packages#699]
I am using highchart lib, but under advanced compilation, there are errors:

```
TypeError: this.Be is undefined


...function(){var b=this.x,c=this.point.y,d=this.Be.name,e=Hs(a,Pg.j(d),b);return[y...

```

it looks like for code:

```
(let [x (.-x obj)
            y (-> obj .-point .-y)
            name (.-name (.-series obj))
```

why it keeps x, point,y, but renamed series? is there a way to fix it?

Thanks!

**Comment by Deraen** [comment]
`series` property is missing from the extern file: https://github.com/cljsjs/packages/blob/master/highcharts/resources/cljsjs/highcharts/common/highcharts.ext.js

**Comment by Deraen** [comment]
https://github.com/cljsjs/packages/commit/974c76441690ea2c9678a30738f295012b928f27
