### ISSUE TITLE
[react-datepicker] newest version missing object-assign-shim

### ISSUE THREAD

**Issue by calvis** [cljsjs/packages#703]
Using the current version `[cljsjs/react-datepicker "0.28.2-0"]` causes

```
Uncaught Error: Undefined nameToPath for cljsjs.object_assign_shim
```

It looks like this got a fix in https://github.com/cljsjs/packages/pull/689 but I believe `react-datepicker` needs to be updated to use the new version of `react-onclickoutside`?

**Comment by adstage-david** [comment]
I totally missed that when I was asked to bump the library version - pushed up a fix that should work.
