### ISSUE TITLE
d3.js 4.2 externs are incomplete

### ISSUE THREAD

**Issue by OliverM** [cljsjs/packages#707]
The d3.js 4.2 externs don't cover the x0, x1, y0 and y1 functions of the area object. I've patched these in my own app using the following externs declarations, but I'm not sure how they fit in to the main d3 externs file. I'm happy to integrate them and do a pull request if anyone has any tips? There may be other gaps in the externs but these are the ones I've encountered so far:

```js
d3.area.y0=function(_){};
d3.area.y1=function(_){};
d3.area.x0=function(_){};
d3.area.x1=function(_){};
```

**Comment by ducky427** [comment]
@OliverM, you can edit [this externs](https://github.com/cljsjs/packages/blob/master/d3/resources/cljsjs/d3/common/d3.ext.js) file and send a PR. Please do document what bits you've added manually.

Thanks!

**Comment by OliverM** [comment]
Thanks @ducky427, just did a pull request #708. Happy to take guidance if I'm not getting this whole externs generation thing yet!

**Comment by Deraen** [comment]
PR has been merged.
