### ISSUE TITLE
Update auth0-lock

### ISSUE THREAD

**Issue by agzam** [cljsjs/packages#710]
I have never updated a cljsjs package before and this seem to be rather urgent issue. There's a critical vulnerability in auth0-lock, version that's being used right now `[cljsjs/auth0-lock "9.2.1-0"]`, see: https://support.auth0.com/notifications/5733ac85696acf110039b3c2

Also it may be as easy as just bumping up the version number. Can someone do that? Thanks!

**Comment by ducky427** [comment]
@agzam, if its that easy, could you please send a PR.

**Comment by ducky427** [comment]
I think this fixed by #712. So closing this.
