### ISSUE TITLE
Documentation for publishing: Explain `checksum` use in download task.

### ISSUE THREAD

**Issue by dvingo** [cljsjs/packages#714]
I just went through the packaging process for the first time and it went pretty smoothly, the only thing that I didn't find explained was the use of the `checksum` keyword in the download task of https://github.com/cljsjs/boot-cljsjs. It was pretty easy to figure out that I needed to produce the md5 sum of the zip and then set this in the boot task, but it wasn't mentioned in the documentation. It would be great if there was info on which checksum algorithm is used, what it is used for (why it is needed) and how to create a checksum on various platforms.

Thanks!

**Comment by martinklepsch** [comment]
If you run `boot download --help` an explanation for each possible parameter will be printed.

 I assume you went through [this guide](https://github.com/cljsjs/packages/wiki/Creating-Packages)? If so feel free to edit it. It's a community wiki so if you think you can contribute something that will help others down the line that is *very* welcome! :)

**Comment by dvingo** [comment]
Thanks for the feedback! Yep, I went through the guide, it does mention it, but only in passing. I made some updates that expands on how to compute and set the checksum.

**Comment by binarykitchen** [comment]
same here, i wonder how i can get the checksum of a certain library?

**Comment by dvingo** [comment]
@binarykitchen Check the guide https://github.com/cljsjs/packages/wiki/Creating-Packages there is a note about how to get the checksum, does that help you out?

**Comment by Deraen** [comment]
Just edited that wiki page yesterday and it now reads:

>  If the :checksum option is empty string or incorrect, and error containing the real MD5 checksum is displayed and you can use this to fix the value.

Is that clear enough? There are other ways but that's what I do myself and it doesn't require manually downloading files and running other commands.

**Comment by binarykitchen** [comment]
thanks guys but now I am seeing a null pointer exception when calling `boot download` and `boot package` doesn't print a checksum.

**Comment by dvingo** [comment]
Woah! Do you have a fork that we can take a look at?

**Comment by binarykitchen** [comment]
never mind, it was my mistake - all good now
