### ISSUE TITLE
[Issue] Codemirror Addons Failing

### ISSUE THREAD

**Issue by flyboarder** [cljsjs/packages#721]
It seems how codemirror is packaged does not work, after including the addons I am seeing many errors. (33+ errors)

Addons etc. are interdependent and currently not correctly bundled correctly. They need to be built via browserify.

**Comment by Deraen** [comment]
I'm quite sure the addons should work, they seem to contain UMD loader which works on browser: https://github.com/codemirror/CodeMirror/blob/master/addon/comment/comment.js#L9
