### ISSUE TITLE
[Request] firebase 3.4.0

### ISSUE THREAD

**Issue by lsenta** [cljsjs/packages#746]
Last versions includes fixes with auth, etc.
https://firebase.google.com/support/release-notes/js

I tried following the readme so just bumping the versions:
https://github.com/lsenta/packages/commit/1cfc8766258dfcb80c9a8197e73ba67777b7a814

However, when I `boot package jar install` then use it in my project, I get:

```
-- Error --
ReferenceError: require is not defined(anonymous function) @ firebase.inc.js:formatted:8

-- firebase.inc:formatted --
/**
 *  Firebase libraries for browser - npm package.
 *
 * Usage:
 *
 *   firebase = require('firebase');
 */
var firebase = require('./app');
require('./auth');
require('./database');
require('./storage');
module.exports = firebase;
```

I'm don't know where to go from there. It's probably a silly misconf. If someone more knowledgeable can take a look or provide me with guidance... thanks!

**Comment by lsenta** [comment]
I tried to download the bundled from gstatic package instead:

https://github.com/lsenta/packages/commits/firebase-3-4-0

Seem's to work in dev mode with no optimizations.
Not sure that's the right approach especially with optimizations.

**Comment by flyboarder** [comment]
@lsenta @Deraen This will depend on cljsjs/boot-cljsjs#39

**Comment by Deraen** [comment]
@flyboarder There is plenty of packages already packaged without using any npm tasks, e.g. https://github.com/cljsjs/packages/blob/fdc466ba9ab30bfbbd9fb83cbd8d5914fa9bdc77/react-date-range/build.boot#L41.

**Comment by flyboarder** [comment]
@Deraen I wasn't aware the build env already had access to these tools (npm & webpack), I'll look at a patch for the Firebase package then.

**Comment by Deraen** [comment]
Yep :) Circle has Node/NPM available.

**Comment by flyboarder** [comment]
Firebase is now past 3.5 cljsjs has been updated. This can be closed.

**Comment by lsenta** [comment]
thanks guys!

**Comment by theronic** [comment]
A one liner on how to use Firebase externs in README would go a long way :)
