### ISSUE TITLE
Fixed-data-table clojar deploy problem

### ISSUE THREAD

**Issue by olivergeorge** [cljsjs/packages#76]
I did my first clojar deploy to release fixed-data-table but I'm having some trouble using it.  I'm wondering if anyone can see something obviously wrong.

This is a demo project which I'm using to test:
https://github.com/ul/fixed-data-table-demo

When I run "boot package build-jar install" and use a locally installed version it works.

When I use "lein cljsbuild once" using the package from clojars it fails with this error:

> Caused by: clojure.lang.ExceptionInfo: No such namespace: cljsjs.fixed-data-table, could not locate cljsjs/fixed_data_table.cljs at line 1 src/fixed_data_table_demo/core.cljs {:tag :cljs/analysis-error, :file "src/fixed_data_table_demo/core.cljs", :line 1, :column 1}

This is the package on clojars:
https://clojars.org/cljsjs/fixed-data-table

Thanks, Oliver

**Comment by ul** [comment]
What is your deploy command? `boot package build-jar push-release`?

`0.1.2-1` jar is missing files generated by `package` task, i suppose you missed its invocation.

**Comment by olivergeorge** [comment]
That fits.

I was using `boot build-jar push-release` based on the clojar pushing doco:
https://github.com/ato/clojars-web/wiki/pushing

I'll retry now...

**Comment by olivergeorge** [comment]
That was it.  Thanks for the looking at that for me.
