### ISSUE TITLE
[react-select] Can't require react-select

### ISSUE THREAD

**Issue by ar7hur** [cljsjs/packages#845]
Adding `[cljsjs/react-select "1.0.0-rc.1"]` to dependencies seems to break React (`js/React` becomes undefined). Here is the relevant portion of `project.clj`:

```
:dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.229"]
                 [org.clojure/core.async "0.2.391"
                  :exclusions [org.clojure/tools.reader]]
                 [reagent "0.6.0" :exclusions [cljsjs/react]]
                 [cljsjs/react-with-addons "15.2.1-0"]
                 [secretary "1.2.3"]
                 [cljsjs/react-select "1.0.0-rc.1"]]
```

**Comment by Deraen** [comment]
I guess the problem is that you want to use react-with-addons but react-select brings in normal react dependency.

Check `lein deps :tree` and add `:exclusions [cljsjs/react]` to `react-select`. Or use global exclusions.
