### ISSUE TITLE
Uncaught TypeError: d3.functor is not a function

### ISSUE THREAD

**Issue by devasiajoseph** [cljsjs/packages#902]
When I try to use d3-tip I am getting an error:

```
Uncaught TypeError: d3.functor is not a function
    at Function.tip.html (d3-tip.inc.js:144)
```

Here is my code :

`(-> js/d3 (.tip) (.attr "class" "d3-tip") (.html (fn [d] d))) `

This will work if I include d3 and d3-tip files as script tags inside html.

The raw javascript code is :

tip = d3.tip().attr('class', 'd3-tip').html(function(d) { return d; });

What did I miss ?

**Comment by miikka** [comment]
Which version of D3 are you using? I'm asking because [D3 4.x removed](https://github.com/d3/d3/blob/f797dfe883ee510f32acadf3ab8be736146e5927/CHANGES.md#internals) the `d3.functor` function and I believe that d3-tip 0.6.7 only works with D3 3.x.

**Comment by devasiajoseph** [comment]
@miikka I guess that might be the problem. I was using [cljsjs/d3 "4.3.0-2"].   Also, I see c3 breaks too with the latest version of d3. Thank you for your suggestion.
