### ISSUE TITLE
jsbn question

### ISSUE THREAD

**Issue by upgradingdave** [cljsjs/packages#904]
I'd like to use the AWS Cognito js sdk from clojurescript. It looks like aws-cognito-js has a dependency on `jsbn.js`. I noticed that `jsbn.js` is included inside the `forge` js project and also in the corresponding `forge` cljsjs package. 

But, unfortunately, I think AWS Cognito js lib expects to find `BigInteger`, whereas the cljsjs package exports `forge.jsbn.BigInteger`. 

I can create a new `jsbn` package, but then jsbn code will be in two cljsjs packages, which seems less than ideal. 

Any suggestions?

**Comment by upgradingdave** [comment]
Just wanted to elaborate in hopes of clarifying a little bit. Ultimately, I'd like to create a cljsjs package for the AWS Cognito js sdk. 

The AWS Cognito js sdk depends on `jsbn.js`, and `jsbn2.js` as well as a few other js libraries. 

I see `jsbn` is already included in cljsjs package called `forge`, I'm wondering if I should try to use that somehow?

Here are a few options for creating aws-cognito-js package I've thought of. Just curious if one of these options is preferred over another?

- Option 1: create a single `aws-cognito-js` package that downloads the `jsbn.js` and `jsbn2.js`, along with aws-cognito-sdk.js and then munges them all together to create a single `aws-cognito.js` file which I can then move to `development/aws-cognito.inc.js` and `production/aws-cognito.min.inc.js`
- Option 2: create `jsbn` cljsjs package and a `jsbn2` package and then create the `aws-cognito` cljsjs package to depend on those two.
- Option 3: I'm not sure whether this is possible, but maybe somehow make the `aws-cognito` depend on the existing `forge` package? I don't think this will work because I assume `aws-cognito-sdk` looks for `BigInteger` instead of `forge.jsbn.BigInteger`.

I'm leaning toward Option 2.

**Comment by miikka** [comment]
It seems rather coincidental that Forge contains jsbn, so option 3 does not make sense to me. Option 2 sounds good.

**Comment by Deraen** [comment]
What is the library for jsbn and jsbn2? This one https://github.com/jasondavies/jsbn ?

If yes, that library could be packaged as one Cljsjs package: `cljsjs/jsbn` which provides both `cljsjs.jsbn` and `cljsjs.jsbn2` (just write `deps.cljs` by hand instead of `deps-cljs` task).

**Comment by upgradingdave** [comment]
Thanks much for the suggestions, I'll go with option 2. The aws docs suggest using the jsbn files [here](http://www-cs-students.stanford.edu/~tjw/jsbn/), but looks like https://github.com/jasondavies/jsbn is a more up-to-date version, so I might go with that one, thanks again.
