### ISSUE TITLE
PIXI js has incomplete externs

### ISSUE THREAD

**Issue by thedavidmeister** [cljsjs/packages#906]
When PIXI was initially committed it had externs for all the prototypes, e.g. `PIXI.Graphics.prototype`, `PIXI.Text.prototype`, etc.

https://github.com/cljsjs/packages/pull/131/files#diff-2c5ba10c88fd4514287a13460627e125

They seem to be missing now, and this is causing breakages for me. I copied and pasted what seemed relevant from the original commit and now my setup is working again.

**Comment by miikka** [comment]
I regenerated the externs and they now again include `PIXI.Graphics.prototype` etc. @thedavidmeister, could you check if `[cljsjs/pixi "4.0.3-1"]` works for you?

**Comment by thedavidmeister** [comment]
@miikka i've put a ticket up to check this out, but not sure when i'll get to it exactly. Thanks for looking into this :)

**Comment by miikka** [comment]
I'll close this issue now, but if you find that it does not work, please reopen.

**Comment by thedavidmeister** [comment]
@miikka aah, i did actually start using this. Forgot to report back >.< it works fine, thanks!
