### ISSUE TITLE
Adding a package template for getting started?

### ISSUE THREAD

**Issue by RadicalZephyr** [cljsjs/packages#93]
It seems to me that it might be helpful for jump-starting people to have some form of a template to help people get started on packaging.

Since what's needed is fairly minimal this could probably be just a directory that has the basic structure already there.  But it might be nicer to have something a little bit smarter, akin to a lein-new template.  It feels wrong to require lein to be installed just to take advantage of the template though...

**Comment by martinklepsch** [comment]
I, and most others, just copy one of the existing packages and modify them. It's a bit of a hack but works well and allows people to select the most similar package as a template.

**Comment by RadicalZephyr** [comment]
That's fair I suppose.  Would you be opposed to including such a tool if I were to make it? I think the benefit of it would mainly be for people new to packaging for cljsjs as a way to get started.

**Comment by martinklepsch** [comment]
I wouldn't be opposed! :smile: 

I'd like to see such thing being integrated into the rest of the CLJSJS tooling in `boot-cljsjs` though — is that something you can align with?

**Comment by RadicalZephyr** [comment]
Absolutely!  That seems like a good place for the actual task definition.

Maybe a root `build.boot` file could also be added so that a new package could be templated easily with something like `boot new-package <package-name>`?

**Comment by martinklepsch** [comment]
Yeah, that sounds handy. Although boot makes it pretty easy to import tasks from dependencies as well:
```
boot -d boot-cljs cljs
```

**Comment by martinklepsch** [comment]
Closing this. Please feel free to reopen if there's anything you'd like to discuss.
