### ISSUE TITLE
upgrade react 15.4.2

### ISSUE THREAD

**Issue by zowers** [cljsjs/packages#934]
please update react to recently released 15.4.2
https://github.com/facebook/react/releases/tag/v15.4.2

**Comment by ducky427** [comment]
React v15.4.2 isn't published at `https://facebook.github.io/react/downloads/react-15.4.2.zip` unlike other releases. So we'll need to download the files from somewhere else for it.

**Comment by zowers** [comment]
reported as https://github.com/facebook/react/issues/8773

**Comment by mogadanez** [comment]
@ducky427 maybe need used npm instead of  direct download?
https://github.com/cljsjs/packages/blob/a83eac210eb6346209480ee2c34be6ce586e91af/react/build.boot#L80

**Comment by ducky427** [comment]
@mogadanez, there is a good chance that it may not work as we need a 'browserified' version of React. But I may be wrong on this.

**Comment by gaearon** [comment]
>there is a good chance that it may not work as we need a 'browserified' version of React. 

They are available in the npm packages, just like they have been since initial releases.
Please see my reply in https://github.com/facebook/react/issues/8773#issuecomment-272435880.

**Comment by Deraen** [comment]
Updated.
