### ISSUE TITLE
dependencies are not pulled in in cljsjs.react-dates

### ISSUE THREAD

**Issue by ludwinas** [cljsjs/packages#941]
I added `[cljsjs/react-dates "3.4.0-1"]` to my project; after compiling the browser console showed `Uncaught Error: Undefined nameToPath for cljsjs.moment`.

This lead me to poke around dependencies and figure out that react-dates's dependencies don't seem to be correctly configured in the build.boot: they are set [in the `deps-cljs` task](https://github.com/cljsjs/packages/blob/master/react-dates/build.boot#L61) but not as `:dependencies` at the [beginning of the file](https://github.com/cljsjs/packages/blob/master/react-dates/build.boot#L3).

P.S. There is also a much newer version of react-date out there (4.3.2) which fixes this issue https://github.com/airbnb/react-dates/issues/188

**Comment by Deraen** [comment]
I fixed the deps, please create PR to update the version.
